import type { CollectionPlanTemplate } from "./types";

export const COLLECTION_PLAN_TEMPLATES: CollectionPlanTemplate[] = [
  {
    id: "general-evidence-record",
    name: "General Evidence Record",
    description: "Balanced intake for primary evidence and supporting context.",
    locationRequirement: "recommended",
    steps: [
      {
        id: "primary_evidence",
        title: "Primary evidence file",
        description: "Upload the principal evidence item that establishes the record.",
        purposeLabel: "Primary evidence",
        required: true,
        acceptedKinds: ["PHOTO", "VIDEO", "AUDIO", "DOCUMENT"],
      },
      {
        id: "supporting_context",
        title: "Supporting context",
        description: "Add supplemental evidence or context files that support the main record.",
        purposeLabel: "Supporting context",
        required: false,
        acceptedKinds: ["PHOTO", "VIDEO", "AUDIO", "DOCUMENT"],
      },
      {
        id: "context_statement",
        title: "Context statement",
        description: "Add an optional audio or video statement for additional context.",
        purposeLabel: "Context statement",
        required: false,
        acceptedKinds: ["AUDIO", "VIDEO"],
      },
    ],
  },
  {
    id: "insurance-claim",
    name: "Insurance Claim",
    description: "Capture damage, policy documentation, and ownership context.",
    locationRequirement: "recommended",
    steps: [
      {
        id: "primary_overview_media",
        title: "Primary overview photo/video",
        description: "Capture a high-level image or video overview of the insured loss.",
        purposeLabel: "Primary overview media",
        required: true,
        acceptedKinds: ["PHOTO", "VIDEO"],
      },
      {
        id: "primary_damage_close_up",
        title: "Primary damage close-up",
        description: "Capture close-up evidence of damage or loss.",
        purposeLabel: "Primary damage close-up",
        required: true,
        acceptedKinds: ["PHOTO", "VIDEO"],
      },
      {
        id: "supporting_ownership_document",
        title: "Supporting ownership or policy document",
        description: "Upload documentation related to ownership or policy coverage.",
        purposeLabel: "Supporting ownership or policy document",
        required: true,
        acceptedKinds: ["DOCUMENT"],
      },
      {
        id: "context_audio_statement",
        title: "Context audio statement",
        description: "Add an optional audio statement describing the incident.",
        purposeLabel: "Context audio statement",
        required: false,
        acceptedKinds: ["AUDIO"],
      },
    ],
  },
  {
    id: "legal-matter",
    name: "Legal Matter",
    description: "Collect primary documents, supporting exhibits, and source notes.",
    locationRequirement: "optional",
    steps: [
      {
        id: "primary_document_media",
        title: "Primary document/media",
        description: "Upload the main document or media item that is being preserved.",
        purposeLabel: "Primary document/media",
        required: true,
        acceptedKinds: ["DOCUMENT", "PHOTO", "VIDEO", "AUDIO"],
      },
      {
        id: "supporting_exhibit",
        title: "Supporting exhibit",
        description: "Attach supporting exhibits or evidence items.",
        purposeLabel: "Supporting exhibit",
        required: false,
        acceptedKinds: ["DOCUMENT", "PHOTO", "VIDEO", "AUDIO"],
      },
      {
        id: "context_source_note",
        title: "Context source note",
        description: "Provide a source or context note for the evidence.",
        purposeLabel: "Context source note",
        required: false,
        acceptedKinds: ["DOCUMENT"],
      },
      {
        id: "supporting_timeline_evidence",
        title: "Supporting timeline evidence",
        description: "Attach timeline evidence such as logs or recordings.",
        purposeLabel: "Supporting timeline evidence",
        required: false,
        acceptedKinds: ["DOCUMENT", "PHOTO", "VIDEO", "AUDIO"],
      },
    ],
  },
  {
    id: "incident-investigation",
    name: "Incident / Investigation",
    description: "Capture scene overview, close-up detail, and witness media.",
    locationRequirement: "required",
    steps: [
      {
        id: "primary_scene_overview",
        title: "Primary scene overview",
        description: "Capture an overview image or video of the incident scene.",
        purposeLabel: "Primary scene overview",
        required: true,
        acceptedKinds: ["PHOTO", "VIDEO"],
      },
      {
        id: "primary_close_up_detail",
        title: "Primary close-up detail",
        description: "Capture close-up detail of the relevant evidence.",
        purposeLabel: "Primary close-up detail",
        required: true,
        acceptedKinds: ["PHOTO", "VIDEO"],
      },
      {
        id: "supporting_witness_statement",
        title: "Supporting witness/media statement",
        description: "Add a witness statement or media statement for context.",
        purposeLabel: "Supporting witness/media statement",
        required: false,
        acceptedKinds: ["AUDIO", "VIDEO", "DOCUMENT"],
      },
      {
        id: "supporting_file_log",
        title: "Supporting file/log",
        description: "Attach supporting files such as logs, extracts, or reports.",
        purposeLabel: "Supporting file/log",
        required: false,
        acceptedKinds: ["DOCUMENT", "PHOTO", "VIDEO", "AUDIO"],
      },
    ],
  },
  {
    id: "compliance-audit",
    name: "Compliance Audit",
    description: "Collect policy, audit evidence, and supporting records for review.",
    locationRequirement: "recommended",
    steps: [
      {
        id: "primary_policy_document",
        title: "Primary policy / compliance document",
        description: "Upload the policy, audit document, or compliance file being preserved.",
        purposeLabel: "Primary policy / compliance document",
        required: true,
        acceptedKinds: ["DOCUMENT"],
      },
      {
        id: "primary_export_supporting_evidence",
        title: "Primary export / supporting evidence",
        description: "Upload the export, screenshot, or supporting evidence file for the compliance record.",
        purposeLabel: "Primary export / supporting evidence",
        required: true,
        acceptedKinds: ["PHOTO", "VIDEO", "DOCUMENT"],
      },
      {
        id: "supporting_audit_evidence",
        title: "Supporting audit evidence",
        description: "Add any additional supporting evidence for the audit record.",
        purposeLabel: "Supporting audit evidence",
        required: false,
        acceptedKinds: ["PHOTO", "VIDEO", "AUDIO", "DOCUMENT"],
      },
      {
        id: "context_reviewer_note",
        title: "Context reviewer note",
        description: "Provide an internal note for reviewer context and intake rationale.",
        purposeLabel: "Context reviewer note",
        required: false,
        acceptedKinds: ["DOCUMENT"],
      },
    ],
  },
  {
    id: "journalism-field-capture",
    name: "Journalism / Field Capture",
    description: "Collect primary media, scene context, and source-safe notes.",
    locationRequirement: "recommended",
    steps: [
      {
        id: "primary_media",
        title: "Primary media",
        description: "Upload the primary media item for the field report.",
        purposeLabel: "Primary media",
        required: true,
        acceptedKinds: ["PHOTO", "VIDEO"],
      },
      {
        id: "supporting_scene_context",
        title: "Supporting scene/context capture",
        description: "Capture scene context to support the primary media.",
        purposeLabel: "Supporting scene/context capture",
        required: true,
        acceptedKinds: ["PHOTO", "VIDEO"],
      },
      {
        id: "context_source_safe_note",
        title: "Context source-safe note",
        description: "Add an optional source-safe note for the evidence record.",
        purposeLabel: "Context source-safe note",
        required: false,
        acceptedKinds: ["DOCUMENT"],
      },
      {
        id: "supporting_document",
        title: "Supporting document",
        description: "Attach any supporting documents or transcripts.",
        purposeLabel: "Supporting document",
        required: false,
        acceptedKinds: ["DOCUMENT"],
      },
    ],
  },
];

export const ROLE_SUGGESTIONS = [
  "Primary evidence",
  "Supporting document",
  "Scene overview",
  "Damage close-up",
  "Identity / ownership proof",
  "System log / export",
  "Witness or audio statement",
  "Other",
];

export const MAX_SESSION_FILES = 50;
export const MAX_SINGLE_FILE_BYTES = 500 * 1024 * 1024;
export const MAX_SESSION_BYTES = 2 * 1024 * 1024 * 1024;

export const GENERIC_EVIDENCE_UPLOAD_ACCEPT =
  "image/*,video/*,audio/*,application/pdf,text/*,application/json,application/xml,text/xml,application/zip,application/x-zip-compressed,.csv,.log,.txt,.rtf,.doc,.docx,.xls,.xlsx,.eml,.msg,.zip,.json,.xml";