/**
 * THE DESTRUCTION CANDIDATE REPORT — read-only, and structurally unable to be
 * anything else.
 *
 * WHY THIS EXISTS
 * ---------------------------------------------------------------------------
 * Automatic physical destruction ships disabled (see
 * `AUTOMATIC_EVIDENCE_DESTRUCTION_ENABLED` in the trash-grace reconciler). The
 * intended path to enabling it is: run this, read what it says, satisfy
 * yourself that every record it names SHOULD go, then turn the flag on. That is
 * only a meaningful safeguard if the report and the destroyer agree exactly —
 * a report generated by a second, independent implementation would be a
 * different opinion about the same records, and the operator would be
 * approving the wrong list.
 *
 * So this does not re-implement anything. It calls
 * `runTrashGraceReconciliation({ dryRun: true })` — the same scan, the same
 * hold resolution, the same approval resolution, the same
 * `evaluateDestructionCandidate` from `@proovra/shared`. `dryRun` suppresses
 * every write INCLUDING the destruction-review creation, and it does so
 * independently of the production flag, so running this in a workspace where
 * automatic destruction is already enabled cannot be the thing that triggers a
 * destruction.
 *
 * Usage (after `pnpm --filter @proovra/worker build`):
 *   pnpm --filter @proovra/worker destruction-candidates -- [--team=<uuid>] [--limit=N] [--json]
 *
 * Exit codes:
 *   0  report produced (whatever it found — "nothing eligible" is a result)
 *   1  the report could not be produced
 */

import { runTrashGraceReconciliation } from "../governance/trash-grace-reconciler.js";

function arg(name: string, fallback: string | null = null): string | null {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
}

/** Fixed-width, so a long list stays readable in a terminal. */
function pad(value: unknown, width: number): string {
  const s = value === null || value === undefined ? "-" : String(value);
  return s.length >= width ? s.slice(0, width) : s.padEnd(width);
}

function day(iso: string | null): string {
  return iso ? String(iso).slice(0, 10) : "-";
}

async function main() {
  const teamId = arg("team");
  const limit = Number(arg("limit", "500"));
  const asJson = process.argv.includes("--json");

  const report = await runTrashGraceReconciliation({
    dryRun: true,
    teamId,
    batchSize: Number.isFinite(limit) && limit > 0 ? limit : 500,
    trigger: "candidate_report",
  });

  if (asJson) {
    process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
    return;
  }

  console.log("");
  console.log("EVIDENCE DESTRUCTION CANDIDATES (read-only)");
  console.log("===========================================================");
  console.log(`run                 ${report.runId}`);
  console.log(`workspace           ${teamId ?? "(all)"}`);
  console.log(`scanned             ${report.scanned} trashed records past grace`);
  console.log(`eligible now        ${report.eligible}`);
  console.log(`blocked             ${report.blocked}`);
  console.log(
    `automatic destroy   ${report.observeOnly ? "DISABLED (observe only)" : "ENABLED"}`,
  );
  console.log("");

  if (report.candidates.length === 0) {
    console.log("No trashed record has passed its recovery grace window.");
    console.log("");
    return;
  }

  console.log(
    [
      pad("evidence", 38),
      pad("state", 22),
      pad("grace", 11),
      pad("app-ret", 11),
      pad("obj-lock", 11),
      pad("mode", 11),
      pad("hold", 5),
      pad("appr", 6),
      "reason",
    ].join(" "),
  );
  console.log("-".repeat(140));

  for (const c of report.candidates) {
    console.log(
      [
        pad(c.evidenceId, 38),
        pad(c.disposition, 22),
        pad(day(c.trashGraceUntilUtc), 11),
        pad(day(c.appRetentionUntilUtc), 11),
        pad(day(c.objectLockRetainUntilUtc), 11),
        pad(c.objectLockMode ?? "-", 11),
        pad(c.legalHold ? "YES" : "no", 5),
        pad(c.approvalRequired ? (c.approved ? "yes" : "NO") : "n/a", 6),
        c.blockReason ?? "ELIGIBLE",
      ].join(" "),
    );
  }

  console.log("");
  console.log(
    `eligible after ${report.candidates.filter((c) => c.destructionEligibleAtUtc).length ? "the dates above" : "no known boundary"}; ` +
      "nothing in this report was modified.",
  );
  console.log("");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("destruction-candidates: failed");
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
