/**
 * UC-3 STREAMING PACKAGE PUBLICATION — disposable MinIO lifecycle harness.
 *
 * Proves the integrity-critical package publication behavior BELOW the queue
 * boundary against real object storage (the Point-7 disposable MinIO), without the
 * full BullMQ/report pipeline:
 *
 *   synthetic source objects → streamed ZIP → local temp → private staging object
 *   → HEAD (exact size) → allowance decision → server-side promotion → HEAD canonical
 *   → cleanup.
 *
 * Run with the local MinIO reachable: `P7_HOST_S3_PORT=59400` selects the disposable
 * instance the Point-7 bootstrap already points at (bucket `point7-local-bucket`).
 */
import { describe, it, expect, afterAll } from "vitest";
import { createHash, randomUUID } from "node:crypto";
import { Readable } from "node:stream";

import {
  copyObject,
  deleteObject,
  getObjectStream,
  headObject,
  putObjectBuffer,
  putObjectFromFile,
} from "../src/storage.js";
import { env } from "../src/config.js";
import {
  streamZipToTempFile,
  cleanupStagedTemp,
  reconcileStaleStaging,
  type StreamingPackageEntry,
} from "../src/verification-package-staging.js";
import { listObjects } from "../src/storage.js";

const BUCKET = env.S3_BUCKET;
const RUN = `uc3pub-${randomUUID()}`;
const created: string[] = [];

async function put(key: string, body: Buffer) {
  await putObjectBuffer({ bucket: BUCKET, key, body, contentType: "application/octet-stream" });
  created.push(key);
}
async function exists(key: string): Promise<boolean> {
  try {
    await headObject({ bucket: BUCKET, key });
    return true;
  } catch {
    return false;
  }
}
async function streamToBuffer(s: Readable): Promise<Buffer> {
  const chunks: Buffer[] = [];
  for await (const c of s) chunks.push(typeof c === "string" ? Buffer.from(c) : (c as Buffer));
  return Buffer.concat(chunks);
}

afterAll(async () => {
  for (const key of created) await deleteObject({ bucket: BUCKET, key }).catch(() => {});
});

describe("UC-3 streaming package publication — disposable MinIO", () => {
  it("A. success: stream → staging → exact size → allow → promote → canonical verified → cleanup", async () => {
    // Synthetic ORIGINAL parts already in storage.
    const p0 = Buffer.from("segment-0-bytes-".repeat(1000));
    const p1 = Buffer.from("segment-1-bytes-".repeat(2000));
    const k0 = `${RUN}/src/part-0.mp4`;
    const k1 = `${RUN}/src/part-1.mp4`;
    await put(k0, p0);
    await put(k1, p1);

    // Stream a package from the storage objects + a small manifest — never buffering.
    const entries: StreamingPackageEntry[] = [
      { name: "evidence-manifest.json", buffer: Buffer.from(JSON.stringify({ parts: 2 })) },
      { name: "evidence-parts/part-0.mp4", source: () => getObjectStream({ bucket: BUCKET, key: k0 }) as unknown as Promise<Readable> },
      { name: "evidence-parts/part-1.mp4", source: () => getObjectStream({ bucket: BUCKET, key: k1 }) as unknown as Promise<Readable> },
    ];
    const staged = await streamZipToTempFile(entries);

    // Upload to the PRIVATE staging key (streamed from temp, exact ContentLength).
    const stagingKey = `internal/package-staging/${RUN}/v1.zip`;
    await putObjectFromFile({ bucket: BUCKET, key: stagingKey, filePath: staged.tempPath, contentLength: staged.sizeBytes, contentType: "application/zip" });
    created.push(stagingKey);
    await cleanupStagedTemp(staged);

    // Staging exists and is EXACTLY the generated bytes.
    const stagingHead = await headObject({ bucket: BUCKET, key: stagingKey });
    expect(Number(stagingHead.sizeBytes)).toBe(staged.sizeBytes);
    // Its bytes hash to the generated digest (end-to-end streaming integrity).
    const stagingBytes = await streamToBuffer((await getObjectStream({ bucket: BUCKET, key: stagingKey })) as unknown as Readable);
    expect(createHash("sha256").update(stagingBytes).digest("hex")).toBe(staged.sha256Hex);

    // Staging is NOT canonical — the user-visible canonical object does not exist yet.
    const canonicalKey = `verification/${RUN}/v1.zip`;
    expect(await exists(canonicalKey)).toBe(false);

    // ALLOWANCE PASSES (simulated) → server-side PROMOTE → verify canonical.
    await copyObject({ sourceBucket: BUCKET, sourceKey: stagingKey, destBucket: BUCKET, destKey: canonicalKey, contentType: "application/zip" });
    created.push(canonicalKey);
    const canonicalHead = await headObject({ bucket: BUCKET, key: canonicalKey });
    expect(Number(canonicalHead.sizeBytes)).toBe(staged.sizeBytes);

    // Cleanup staging; canonical remains available.
    await deleteObject({ bucket: BUCKET, key: stagingKey });
    expect(await exists(stagingKey)).toBe(false);
    expect(await exists(canonicalKey)).toBe(true);
  });

  it("B. refusal: staging exists, gate refuses → staging removed, canonical never appears", async () => {
    const staged = await streamZipToTempFile([{ name: "m.json", buffer: Buffer.from("{}") }]);
    const stagingKey = `internal/package-staging/${RUN}-refuse/v1.zip`;
    const canonicalKey = `verification/${RUN}-refuse/v1.zip`;
    await putObjectFromFile({ bucket: BUCKET, key: stagingKey, filePath: staged.tempPath, contentLength: staged.sizeBytes, contentType: "application/zip" });
    await cleanupStagedTemp(staged);
    expect(await exists(stagingKey)).toBe(true);

    // Gate REFUSES → delete staging, never promote.
    await deleteObject({ bucket: BUCKET, key: stagingKey });
    expect(await exists(stagingKey)).toBe(false);
    expect(await exists(canonicalKey)).toBe(false);
  });

  it("C. idempotent promote: a retry re-copies to the same canonical key, one object, exact size", async () => {
    const staged = await streamZipToTempFile([{ name: "m.json", buffer: Buffer.from(JSON.stringify({ a: 1 })) }]);
    const stagingKey = `internal/package-staging/${RUN}-idem/v1.zip`;
    const canonicalKey = `verification/${RUN}-idem/v1.zip`;
    await putObjectFromFile({ bucket: BUCKET, key: stagingKey, filePath: staged.tempPath, contentLength: staged.sizeBytes, contentType: "application/zip" });
    created.push(stagingKey, canonicalKey);
    await cleanupStagedTemp(staged);

    await copyObject({ sourceBucket: BUCKET, sourceKey: stagingKey, destBucket: BUCKET, destKey: canonicalKey, contentType: "application/zip" });
    await copyObject({ sourceBucket: BUCKET, sourceKey: stagingKey, destBucket: BUCKET, destKey: canonicalKey, contentType: "application/zip" });
    const head = await headObject({ bucket: BUCKET, key: canonicalKey });
    expect(Number(head.sizeBytes)).toBe(staged.sizeBytes);
  });

  it("E. stale-staging reconciliation reclaims an orphaned staging object (crash residue)", async () => {
    // Simulate a crashed publication: a staging object exists but was never promoted.
    const staged = await streamZipToTempFile([{ name: "m.json", buffer: Buffer.from("{}") }]);
    const stagingKey = `internal/package-staging/${RUN}-orphan/v1.zip`;
    await putObjectFromFile({ bucket: BUCKET, key: stagingKey, filePath: staged.tempPath, contentLength: staged.sizeBytes, contentType: "application/zip" });
    await cleanupStagedTemp(staged);
    expect(await exists(stagingKey)).toBe(true);

    // Reconcile with ttlMs=0 (everything under the staging prefix is "stale") →
    // the orphan is reclaimed; a canonical `verification/` object would be untouched.
    const res = await reconcileStaleStaging({ bucket: BUCKET, listObjects, deleteObject, ttlMs: 0 });
    expect(res.deleted).toBeGreaterThanOrEqual(1);
    expect(await exists(stagingKey)).toBe(false);
  });

  it("D. many-artifact package streams from storage without buffering all parts", async () => {
    const n = 12;
    const keys: string[] = [];
    for (let i = 0; i < n; i++) {
      const k = `${RUN}/many/part-${i}.bin`;
      await put(k, Buffer.from(`part-${i}-`.repeat(500)));
      keys.push(k);
    }
    const entries: StreamingPackageEntry[] = keys.map((k, i) => ({
      name: `evidence-parts/part-${i}.bin`,
      source: () => getObjectStream({ bucket: BUCKET, key: k }) as unknown as Promise<Readable>,
    }));
    const staged = await streamZipToTempFile(entries);
    const stagingKey = `internal/package-staging/${RUN}-many/v1.zip`;
    await putObjectFromFile({ bucket: BUCKET, key: stagingKey, filePath: staged.tempPath, contentLength: staged.sizeBytes, contentType: "application/zip" });
    created.push(stagingKey);
    await cleanupStagedTemp(staged);
    const head = await headObject({ bucket: BUCKET, key: stagingKey });
    expect(Number(head.sizeBytes)).toBe(staged.sizeBytes);
    expect(staged.sizeBytes).toBeGreaterThan(0);
  });
});
