apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'com.proovra.screencapture'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "com.proovra.screencapture"
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 26)
    compileSdkVersion safeExtGet("compileSdkVersion", 34)
    targetSdkVersion safeExtGet("targetSdkVersion", 34)
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  kotlinOptions {
    jvmTarget = "17"
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
