import { AiResult } from "./ai-types.js";
import { AI_LEGAL_DISCLAIMER } from "./ai-policy.js";

// Phase C1 — versioned PROOVRA product-knowledge bundle. This is the curated,
// bounded ground truth the support-chat assistant is grounded in. Bump the
// version when the facts change so promptVersion tracking (C7) stays accurate.
export const PRODUCT_KNOWLEDGE_VERSION = "1.1.0";

export const PROOVRA_PRODUCT_FACTS = {
  version: PRODUCT_KNOWLEDGE_VERSION,
  routes: [
    "Home (/home)", "Capture (/capture)", "Evidence library (/evidence)",
    "Evidence detail (/evidence/:id)", "Cases (/cases)", "Reports", "Search (/search)",
    "Reviewer console (/review)", "Operations (/operations)",
    "Public Trust Center (/trust — public trust/security/compliance portal)",
    "Public Verify (/verify and /verify/:token)", "Billing/Pricing", "Settings",
  ],
  roles: [
    "OWNER and ADMIN can manage workspace settings, members, and AI policy.",
    "MEMBER can capture, organize, and prepare evidence.",
    "VIEWER has read-only access.",
    "Personal workspaces are single-user; team workspaces add shared roles.",
  ],
  lifecycle: [
    "Capture stages an item, then Review & Sign finalizes it.",
    "On finalization the file SHA-256 is recorded, an Ed25519 fingerprint signature is created, and a Verification Package + Report PDF are generated by the worker.",
    "Evidence status flows CREATED → UPLOADING → UPLOADED → SIGNED → REPORTED; FAILED_HASH_MISMATCH on integrity failure.",
  ],
  integrity: [
    "Custody chain: append-only, hash-linked custody events (each references the previous event hash).",
    "TSA: RFC3161 timestamp (best-effort, operator-enabled).",
    "OTS: OpenTimestamps Bitcoin anchoring (best-effort, operator-enabled).",
    "Verification Package: a downloadable ZIP with manifest, checksums, signature, and materials.",
    "Public Verify: a hosted page to check a package/report by token.",
  ],
  boundaries: [
    "PROOVRA records integrity state and technical provenance. It does NOT determine factual truth, authenticity, authorship, identity, intent, liability, fraud, or legal admissibility.",
    "Legal hold and retention are governed by workspace policy and human operators — AI never decides them.",
    "AI is advisory only, optional, and never blocks capture, reports, packages, or verification.",
  ],
  supportedActions: [
    "Explain how to capture, upload, organize, and finalize evidence.",
    "Explain custody/integrity/verification signals and workflow states.",
    "Point users to the right PROOVRA screen or the Billing/Pricing page.",
    "Summarize structured, authorized metadata and suggest next steps.",
  ],
  unsupported: [
    "Determining whether evidence is real, authentic, or admissible.",
    "Identifying people, inferring intent, or assigning liability/fault.",
    "Giving legal advice, court strategy, or medical advice.",
    "Inventing prices, features, certifications, or capabilities not listed here.",
  ],
  help: [
    "Billing/Pricing page for current plan prices.",
    "Trust Hub for provider, privacy, and status disclosure.",
    "PROOVRA support for Enterprise or custom needs.",
  ],
} as const;

/**
 * Bounded grounding section injected into the support-chat system prompt so the
 * assistant answers from PROOVRA facts and refuses to invent unavailable
 * features. Kept curated (not a giant doc blob).
 */
export function buildProductKnowledgePromptSection(): string {
  const f = PROOVRA_PRODUCT_FACTS;
  return [
    `PROOVRA product knowledge (v${f.version}) — ground your answers in these facts and do not invent anything beyond them:`,
    `Screens: ${f.routes.join("; ")}.`,
    `Roles: ${f.roles.join(" ")}`,
    `Evidence lifecycle: ${f.lifecycle.join(" ")}`,
    `Integrity/verification: ${f.integrity.join(" ")}`,
    `Boundaries: ${f.boundaries.join(" ")}`,
    `You can: ${f.supportedActions.join(" ")}`,
    `You cannot: ${f.unsupported.join(" ")}`,
    `If asked for something unsupported, briefly say PROOVRA/AI cannot do that and point to the right screen or human support. Use PROOVRA terminology (Capture, Review & Sign, Verification Package, Public Verify, custody, TSA, OTS).`,
  ].join(" ");
}

export const PROOVRA_PRODUCT_KNOWLEDGE = {
  plans: {
    personal: {
      name: "Personal",
      summary:
        "For individuals who need to preserve, organize, and verify digital evidence records.",
    },
    pro: {
      name: "Pro",
      summary:
        "For advanced evidence workflows with reports, verification packages, and stronger review preparation.",
      pricing:
        "PRO plan pricing is shown on the official PROOVRA Billing/Pricing page. Prices may vary by currency, billing cycle, and enabled add-ons.",
    },
    team: {
      name: "Team",
      summary:
        "For organizations that need shared evidence workflows, team access, roles, review, and billing management.",
    },
    enterprise: {
      name: "Enterprise",
      summary:
        "For organizations that need custom onboarding, compliance workflows, support, and enterprise requirements.",
      pricing:
        "Enterprise pricing is custom and should be discussed with PROOVRA support.",
    },
  },
};

/* ===========================================================================
   DETERMINISTIC PRODUCT ANSWERS
   ===========================================================================

   WHY THIS EXISTS

   Every question in the assistant's own advertised competence — "how do I
   capture evidence", "what is a verification package", "what does TSA failed
   mean" — used to require a live provider call. `answerProductKnowledge` only
   recognised pricing, so everything else fell through to OpenAI. That made the
   assistant's usefulness conditional on an outbound API being reachable,
   enabled, funded and in budget, for questions whose answers are FIXED
   PROPERTIES OF THIS PRODUCT and cannot vary by request.

   The consequence was not merely a slow path. With platform AI disabled the
   policy gate returns 403 before the provider is ever consulted, so the
   assistant could not answer "how do I capture evidence" at all — a question
   it is grounded to answer from facts compiled into this very file.

   WHY IT IS A ROUTER, NOT A SECOND KNOWLEDGE BASE

   The facts already live in `PROOVRA_PRODUCT_FACTS`, which is also what
   `buildProductKnowledgePromptSection` feeds to the model. If these answers
   restated them in their own prose there would be two descriptions of custody
   to keep in step, and the one that drifts is always the one nobody reads.

   So a topic owns only two things: how to RECOGNISE the question, and which
   facts ANSWER it. The prose is the facts. When a fact changes, every surface
   that quotes it changes with it, and `PRODUCT_KNOWLEDGE_VERSION` is the one
   thing to bump.

   WHAT THIS IS NOT

   It is not an intent classifier, and it does not try to be exhaustive. It
   answers what it can prove from the bundle and returns null otherwise, which
   sends the question down the provider path exactly as before. A topic that
   matched but had nothing grounded to say would be worse than no topic.
=========================================================================== */

const F = PROOVRA_PRODUCT_FACTS;

/**
 * A deterministic topic: how to spot it, and what the bundle says about it.
 *
 * `summary` and `suggestions` are composed from `PROOVRA_PRODUCT_FACTS` so
 * this table carries routing, not knowledge.
 */
type ProductTopic = {
  id: string;
  /** Matched against the raw last user message, case-insensitively. */
  match: RegExp;
  summary: string;
  suggestions: string[];
};

/*
 * Arabic is matched alongside English because the scope classifier already
 * accepts Arabic questions (`detectChatLanguage`), and a question that passes
 * that gate in Arabic but missed every topic here would be sent to a provider
 * for an answer this file already holds.
 */
const PRODUCT_TOPICS: readonly ProductTopic[] = [
  {
    id: "capture",
    match: /\b(capture|record evidence|upload|take (a )?(photo|video|screenshot)|new evidence|add evidence)\b|التقاط|تسجيل|رفع/i,
    summary: [
      "Capture is where a new record starts. " + F.lifecycle[0],
      F.lifecycle[1],
      "Until it is finalized the item is staged, so you can check what was captured before anything is signed.",
    ].join(" "),
    suggestions: [
      "Open Capture to stage a new record.",
      "Use Review & Sign to finalize a staged record — this is the step that records the hash and signature.",
      "The Evidence library lists every record and the stage it has reached.",
    ],
  },
  {
    id: "case",
    match: /\bcases?\b|\bmatter\b|قضية|قضايا/i,
    summary:
      "Cases group related evidence records so they can be reviewed and reported together. Records stay in the Evidence library and a case references them, so assigning a record to a case does not move or alter it and does not change its custody chain.",
    suggestions: [
      "Open Cases to create one and give it a name.",
      "Assign records to a case from the Evidence library or from a record's own page.",
      "Reports are produced per record; a case is how the related ones stay together.",
    ],
  },
  {
    id: "verification_package",
    match: /verification package|\bpackage\b|\bmanifest\b|حزمة/i,
    summary: [
      F.integrity[3],
      "It is generated by the worker when a record is finalized, alongside the Report PDF.",
      F.integrity[4],
      "Anyone you send the package or token to can check it without a PROOVRA account.",
    ].join(" "),
    suggestions: [
      "Download the Verification Package from a finalized record.",
      "Use Public Verify (/verify) to check a package or report by token.",
    ],
  },
  {
    id: "tsa",
    match: /\btsa\b|timestamp|rfc\s?3161|ختم الوقت/i,
    summary: [
      F.integrity[1],
      "Best-effort means the timestamp is requested from an external authority and that request can fail — a network problem, or an authority that is unavailable or rejects the request. A failed TSA records that this happened.",
      "It does not mean the evidence is invalid or altered. The file hash, the Ed25519 signature and the custody chain are produced by PROOVRA itself and are unaffected; a failed timestamp means one external corroboration is absent, and the record says so rather than hiding it.",
      "A timestamp cannot be re-requested afterwards: it would attest the retry time, not the original one, so PROOVRA records the failure permanently instead of quietly repairing it.",
    ].join(" "),
    suggestions: [
      "Open the record's Technical Appendix to see the recorded timestamp state.",
      "Operations shows timestamp outcomes across the workspace.",
    ],
  },
  {
    id: "ots",
    match: /\bots\b|opentimestamps|bitcoin|anchor/i,
    summary: [
      F.integrity[2],
      "Anchoring is asynchronous, so a record can read as pending for some time after finalization while it waits for Bitcoin confirmation. That is normal and is not a failure.",
      "Like TSA it is an additional external corroboration, not the basis of the record's integrity.",
    ].join(" "),
    suggestions: ["The record's Technical Appendix shows its anchoring state."],
  },
  {
    id: "custody",
    match: /custody|chain of custody|hash[- ]?link|tamper|سلسلة الحيازة/i,
    summary: [
      F.integrity[0],
      "Because each event carries the hash of the one before it, an event cannot be inserted, removed or reordered without breaking every hash after it.",
      F.lifecycle[1],
    ].join(" "),
    suggestions: [
      "A record's page shows its custody events in order.",
      "The Verification Package contains the custody material for independent checking.",
    ],
  },
  {
    id: "lifecycle_status",
    match: /\bstatus\b|lifecycle|\bsigned\b|\breported\b|hash mismatch|failed_hash|\bstages?\b/i,
    summary: [F.lifecycle[2], F.lifecycle[0], F.lifecycle[1]].join(" "),
    suggestions: [
      "The Evidence library shows each record's current stage.",
      "Operations shows records that need attention across the workspace.",
    ],
  },
  {
    id: "notifications",
    match: /notification|\balerts?\b|إشعار|تنبيه/i,
    summary:
      "Notification preferences are in Settings. The Notifications screen lists what has already been raised, grouped by severity, and Operations is where workspace-wide conditions are tracked.",
    suggestions: [
      "Open Settings to choose which notifications you receive.",
      "Open Notifications to see what has been raised.",
    ],
  },
  {
    id: "roles",
    match: /\brole\b|\bpermissions?\b|\bmembers?\b|\binvite\b|صلاحيات|دعوة/i,
    summary: F.roles.join(" "),
    suggestions: [
      "Workspace members and roles are managed in Settings by an OWNER or ADMIN.",
    ],
  },
  {
    id: "ai_capability",
    match: /what can (the )?ai|ai do|what are you|can you (do|help)|ai (features?|capabilit)|الذكاء الاصطناعي/i,
    summary: [
      "In PROOVRA the assistant is advisory. " + F.supportedActions.join(" "),
      "It cannot: " + F.unsupported.join(" "),
      F.boundaries[2],
    ].join(" "),
    suggestions: [
      "AI can be turned off per workspace in Settings; evidence workflows are unaffected either way.",
      "The Trust Center describes how AI is used and what is sent to a provider.",
    ],
  },
  {
    id: "boundaries",
    match: /\b(authentic|admissib|genuine|forged|deepfake)\b|real or fake|هل هذا حقيقي/i,
    summary: F.boundaries.join(" "),
    suggestions: [
      "PROOVRA records what can be checked — hashes, signatures, custody, timestamps — and the Verification Package lets someone else check it independently.",
    ],
  },
  {
    id: "verify_public",
    match: /public verify|verify (a )?(package|report|token)|how (do|can) (i|we) verify|التحقق/i,
    summary: [F.integrity[4], F.integrity[3]].join(" "),
    suggestions: [
      "Open /verify and enter the token, or open the link that was shared with you.",
      "Public Verify needs no PROOVRA account, which is what makes it usable by a recipient.",
    ],
  },
  {
    id: "trust_center",
    match: /trust center|trust hub|subprocessor|compliance page/i,
    summary:
      "The Trust Center (/trust) is the public portal describing PROOVRA's security, privacy and provider disclosure, including how AI is used and what data leaves the platform.",
    suggestions: ["Open the Trust Center for provider, privacy and status disclosure."],
  },
];

/**
 * Pricing is deliberately NOT a row in the table above.
 *
 * Every other topic answers with a fact. Pricing answers by REFUSING to state
 * a number — prices vary by currency, cycle and add-ons, so the only honest
 * answer is the Billing page. Keeping it separate keeps that asymmetry visible
 * rather than hiding a non-answer among answers.
 */
function isPricingQuestion(text: string): boolean {
  return /\b(price|pricing|cost|premium|primum|pro plan|subscription|billing|how much|اشتراك|سعر|تكلفة|بريميوم|برو)\b/i.test(
    text
  );
}

const PRICING_ANSWER: AiResult = {
  status: "ok",
  summary:
    "PROOVRA plan prices are shown on the official Billing/Pricing page because pricing can vary by currency, billing cycle, and add-ons. The PRO plan is intended for advanced evidence workflows such as reports, verification packages, and reviewer-ready evidence preparation.",
  warnings: [],
  suggestions: [
    "Open Billing/Pricing in PROOVRA to see the current price for your account and currency.",
    "For Enterprise or custom needs, contact PROOVRA support.",
  ],
  flags: [],
  legalDisclaimer: AI_LEGAL_DISCLAIMER,
};

/**
 * Answer from the bundle when the bundle can answer; otherwise return null and
 * let the caller take the provider path.
 *
 * Pricing is checked first for the reason given above. Topics are then tried
 * in declaration order and the FIRST match wins, so the table is ordered with
 * the specific before the general — "verification package" before a bare
 * "verify", TSA before a generic status question.
 */
export function answerProductKnowledge(
  messages: { role: string; content: string }[],
): AiResult | null {
  const lastUserMessage =
    [...messages].reverse().find((m) => m.role === "user")?.content ?? "";
  if (lastUserMessage.trim().length === 0) return null;

  if (isPricingQuestion(lastUserMessage)) return PRICING_ANSWER;

  const topic = PRODUCT_TOPICS.find((t) => t.match.test(lastUserMessage));
  if (!topic) return null;

  return {
    status: "ok",
    summary: topic.summary,
    warnings: [],
    suggestions: [...topic.suggestions],
    flags: [],
    legalDisclaimer: AI_LEGAL_DISCLAIMER,
  };
}

/**
 * The topics this build can answer with no provider at all.
 *
 * The availability endpoint reports this so the panel can say what still works
 * while AI is off, instead of presenting itself as uniformly dead.
 */
export function listGroundedTopicIds(): readonly string[] {
  return ["pricing", ...PRODUCT_TOPICS.map((t) => t.id)];
}
