import { AiResult } from "./ai-types.js";
import { AI_LEGAL_DISCLAIMER } from "./ai-policy.js";

// Phase C1 — versioned PROOVRA product-knowledge bundle. This is the curated,
// bounded ground truth the support-chat assistant is grounded in. Bump the
// version when the facts change so promptVersion tracking (C7) stays accurate.
export const PRODUCT_KNOWLEDGE_VERSION = "1.0.0";

export const PROOVRA_PRODUCT_FACTS = {
  version: PRODUCT_KNOWLEDGE_VERSION,
  routes: [
    "Home (/home)", "Capture (/capture)", "Evidence library (/evidence)",
    "Evidence detail (/evidence/:id)", "Cases (/cases)", "Reports", "Search (/search)",
    "Reviewer console (/review)", "Operations (/operations)",
    "Public Trust Center (/trust — public trust/security/compliance portal)",
    "Public Verify (/verify and /verify/:token)", "Billing/Pricing", "Settings",
  ],
  roles: [
    "OWNER and ADMIN can manage workspace settings, members, and AI policy.",
    "MEMBER can capture, organize, and prepare evidence.",
    "VIEWER has read-only access.",
    "Personal workspaces are single-user; team workspaces add shared roles.",
  ],
  lifecycle: [
    "Capture stages an item, then Review & Sign finalizes it.",
    "On finalization the file SHA-256 is recorded, an Ed25519 fingerprint signature is created, and a Verification Package + Report PDF are generated by the worker.",
    "Evidence status flows CREATED → UPLOADING → UPLOADED → SIGNED → REPORTED; FAILED_HASH_MISMATCH on integrity failure.",
  ],
  integrity: [
    "Custody chain: append-only, hash-linked custody events (each references the previous event hash).",
    "TSA: RFC3161 timestamp (best-effort, operator-enabled).",
    "OTS: OpenTimestamps Bitcoin anchoring (best-effort, operator-enabled).",
    "Verification Package: a downloadable ZIP with manifest, checksums, signature, and materials.",
    "Public Verify: a hosted page to check a package/report by token.",
  ],
  boundaries: [
    "PROOVRA records integrity state and technical provenance. It does NOT determine factual truth, authenticity, authorship, identity, intent, liability, fraud, or legal admissibility.",
    "Legal hold and retention are governed by workspace policy and human operators — AI never decides them.",
    "AI is advisory only, optional, and never blocks capture, reports, packages, or verification.",
  ],
  supportedActions: [
    "Explain how to capture, upload, organize, and finalize evidence.",
    "Explain custody/integrity/verification signals and workflow states.",
    "Point users to the right PROOVRA screen or the Billing/Pricing page.",
    "Summarize structured, authorized metadata and suggest next steps.",
  ],
  unsupported: [
    "Determining whether evidence is real, authentic, or admissible.",
    "Identifying people, inferring intent, or assigning liability/fault.",
    "Giving legal advice, court strategy, or medical advice.",
    "Inventing prices, features, certifications, or capabilities not listed here.",
  ],
  help: [
    "Billing/Pricing page for current plan prices.",
    "Trust Hub for provider, privacy, and status disclosure.",
    "PROOVRA support for Enterprise or custom needs.",
  ],
} as const;

/**
 * Bounded grounding section injected into the support-chat system prompt so the
 * assistant answers from PROOVRA facts and refuses to invent unavailable
 * features. Kept curated (not a giant doc blob).
 */
export function buildProductKnowledgePromptSection(): string {
  const f = PROOVRA_PRODUCT_FACTS;
  return [
    `PROOVRA product knowledge (v${f.version}) — ground your answers in these facts and do not invent anything beyond them:`,
    `Screens: ${f.routes.join("; ")}.`,
    `Roles: ${f.roles.join(" ")}`,
    `Evidence lifecycle: ${f.lifecycle.join(" ")}`,
    `Integrity/verification: ${f.integrity.join(" ")}`,
    `Boundaries: ${f.boundaries.join(" ")}`,
    `You can: ${f.supportedActions.join(" ")}`,
    `You cannot: ${f.unsupported.join(" ")}`,
    `If asked for something unsupported, briefly say PROOVRA/AI cannot do that and point to the right screen or human support. Use PROOVRA terminology (Capture, Review & Sign, Verification Package, Public Verify, custody, TSA, OTS).`,
  ].join(" ");
}

export const PROOVRA_PRODUCT_KNOWLEDGE = {
  plans: {
    personal: {
      name: "Personal",
      summary:
        "For individuals who need to preserve, organize, and verify digital evidence records.",
    },
    pro: {
      name: "Pro",
      summary:
        "For advanced evidence workflows with reports, verification packages, and stronger review preparation.",
      pricing:
        "PRO plan pricing is shown on the official PROOVRA Billing/Pricing page. Prices may vary by currency, billing cycle, and enabled add-ons.",
    },
    team: {
      name: "Team",
      summary:
        "For organizations that need shared evidence workflows, team access, roles, review, and billing management.",
    },
    enterprise: {
      name: "Enterprise",
      summary:
        "For organizations that need custom onboarding, compliance workflows, support, and enterprise requirements.",
      pricing:
        "Enterprise pricing is custom and should be discussed with PROOVRA support.",
    },
  },
};

function isPricingQuestion(text: string): boolean {
  return /\b(price|pricing|cost|premium|primum|pro plan|subscription|billing|how much|اشتراك|سعر|تكلفة|بريميوم|برو)\b/i.test(
    text
  );
}

export function answerProductKnowledge(messages: { role: string; content: string }[]): AiResult | null {
  const lastUserMessage = [...messages].reverse().find((m) => m.role === "user")?.content ?? "";

  if (!isPricingQuestion(lastUserMessage)) return null;

  return {
    status: "ok",
    summary:
      "PROOVRA plan prices are shown on the official Billing/Pricing page because pricing can vary by currency, billing cycle, and add-ons. The PRO plan is intended for advanced evidence workflows such as reports, verification packages, and reviewer-ready evidence preparation.",
    warnings: [],
    suggestions: [
      "Open Billing/Pricing in PROOVRA to see the current price for your account and currency.",
      "For Enterprise or custom needs, contact PROOVRA support.",
    ],
    flags: [],
    legalDisclaimer: AI_LEGAL_DISCLAIMER,
  };
}