/**
 * UC-3 STREAMING PACKAGE CLOSURE — Decision #1.
 *
 * Verification packages are generated by STREAMING, never by materialising the
 * whole ZIP (or all artifact bytes) in RAM, and are published only AFTER the
 * canonical allowance gate has seen the EXACT byte size:
 *
 *   artifacts → streaming ZIP → private temp file (bounded disk, O(1) RAM)
 *            → exact size + incremental SHA-256
 *            → private STAGING object (streamed from the temp file)
 *            → canonical allowance / storage / policy gate
 *               ├── REFUSED  → staging object removed; nothing canonical
 *               └── ALLOWED  → server-side COPY (promote) staging → canonical
 *                              → staging object removed
 *
 * The staging object lives under a private, deterministic namespace that normal
 * users and Public Verify never resolve, is never a completed package, and is
 * cleaned on refusal / failure / retry. Promotion is a server-side copy — the
 * package bytes are never downloaded back into worker RAM.
 */
import { createHash, type Hash } from "node:crypto";
import { createWriteStream } from "node:fs";
import { mkdtemp, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pipeline } from "node:stream/promises";
import { Transform, type Readable } from "node:stream";
import archiver from "archiver";

/** One entry to place in the package ZIP. `source` streams from storage (may be
 *  async, e.g. an S3 getObject); `buffer` is inline (small metadata/manifest). */
export type StreamingPackageEntry =
  | { name: string; buffer: Buffer }
  | { name: string; source: () => Readable | Promise<Readable> };

export type StagedPackage = {
  /** Local private temp file holding the streamed ZIP. Bounded disk, never RAM. */
  tempPath: string;
  tempDir: string;
  sizeBytes: number;
  sha256Hex: string;
  sha256Base64: string;
};

/**
 * A private, deterministic staging key that normal users / Public Verify never
 * resolve. Keyed by (evidence, version) so a job RETRY overwrites the same staging
 * object idempotently rather than leaking a new one per attempt.
 */
export function stagingPackageKey(evidenceId: string, version: number): string {
  return `internal/package-staging/${evidenceId}/v${version}.zip`;
}

/** A pass-through Transform that updates a hash and counts bytes without buffering. */
export class HashingMeter extends Transform {
  readonly hash: Hash = createHash("sha256");
  bytes = 0;
  override _transform(chunk: Buffer, _enc: BufferEncoding, cb: (e?: Error | null) => void): void {
    this.hash.update(chunk);
    this.bytes += chunk.length;
    this.push(chunk);
    cb();
  }
}

/**
 * Stream the entries into a ZIP written to a private temp file, computing the exact
 * byte size and SHA-256 incrementally (never buffering the whole archive). Archiver
 * appends entries sequentially, so at most one artifact stream is active at a time
 * and peak memory stays O(stream chunk), independent of total evidence bytes.
 */
export async function streamZipToTempFile(
  entries: AsyncIterable<StreamingPackageEntry> | Iterable<StreamingPackageEntry>,
  opts: { level?: number } = {},
): Promise<StagedPackage> {
  const tempDir = await mkdtemp(join(tmpdir(), "proovra-pkg-"));
  const tempPath = join(tempDir, "package.zip");

  const archive = archiver("zip", { zlib: { level: opts.level ?? 9 } });
  archive.on("warning", (w: Error & { code?: string }) => {
    if (w.code !== "ENOENT") archive.emit("error", w);
  });
  const meter = new HashingMeter();
  const out = createWriteStream(tempPath);

  // archive → meter (hash + count) → temp file. `pipeline` rejects if any stage
  // errors, and resolves only once the temp file is fully flushed. A source-stream
  // failure destroys the archive, which rejects the pipeline — FAIL CLOSED, never a
  // silently truncated package.
  const drain = pipeline(archive, meter, out);

  const feed = (async () => {
    for await (const entry of entries as AsyncIterable<StreamingPackageEntry>) {
      if ("buffer" in entry) {
        archive.append(entry.buffer, { name: entry.name });
      } else {
        const s = await entry.source();
        s.on("error", (e: Error) => archive.destroy(e));
        archive.append(s, { name: entry.name });
      }
    }
    await archive.finalize();
  })();

  // The pipeline is the authoritative completion/failure signal; if a source errors,
  // `drain` rejects and we surface it even while `feed` is still pending.
  await Promise.all([drain, feed.catch((e) => Promise.reject(e))]);

  const digest = meter.hash.digest();
  const { size } = await stat(tempPath);
  return {
    tempPath,
    tempDir,
    sizeBytes: size,
    sha256Hex: digest.toString("hex"),
    sha256Base64: digest.toString("base64"),
  };
}

/** Remove a staged temp directory, ignoring absence. */
export async function cleanupStagedTemp(staged: Pick<StagedPackage, "tempDir">): Promise<void> {
  try {
    await rm(staged.tempDir, { recursive: true, force: true });
  } catch {
    /* temp hygiene only */
  }
}
