/**
 * Phase A2 — Report artifact + signature bounded vocabulary.
 *
 * Single source of truth for the strings that describe Evidence
 * artifacts on the wire. The backend writes ONLY these literals;
 * the frontend renders signed/unsigned badges ONLY from these
 * literals; tests grep the codebase to keep new strings from
 * leaking in.
 *
 * Two related but distinct artifacts:
 *
 *   1. **Report PDF**  — the human-readable PDF generated by the
 *      worker. May or may not carry a PKCS#12 PDF artifact
 *      signature. Distinct from the Ed25519 fingerprint signature
 *      stored on `evidence.signatureBase64`, which signs the
 *      canonical fingerprint hash and is independent of the PDF
 *      bytes.
 *
 *   2. **Verification Package ZIP** — the offline-verifiable
 *      bundle. Carries its own Ed25519 signature over MANIFEST.json
 *      (see `services/worker/src/verification-package.ts`).
 *      Independent of the Report PDF signature.
 *
 * Vocabulary rule: never collapse these two artifacts under one
 * label. The Phase A2 acceptance tests assert this for every
 * user-facing surface.
 */

export const ARTIFACT_TYPES = [
  "REPORT_PDF",
  "VERIFICATION_PACKAGE_ZIP",
] as const;
export type ArtifactType = (typeof ARTIFACT_TYPES)[number];

export const PDF_SIGNATURE_STATUSES = [
  /** PDF carries a valid PKCS#12 signature attached by the worker. */
  "SIGNED",
  /**
   * Operator-acknowledged unsigned path. Set when
   * `PDF_ARTIFACT_SIGNATURE_OPT_OUT_ACK=true` was the active
   * env at PDF generation time. UI MUST label this case
   * explicitly as "Unsigned Report PDF artifact".
   */
  "UNSIGNED_OPT_OUT",
  /**
   * Non-production environment with signing disabled (local dev,
   * preview). The API response surfaces this distinct from
   * UNSIGNED_OPT_OUT so QA and operators can tell the difference.
   */
  "SIGNING_UNAVAILABLE",
  /**
   * Reserved. Today the worker fails the report job (DLQ) when
   * the PDF signing call throws and never writes a Report row,
   * so this value is never produced for current artifacts. Kept
   * in the enum so a future partial-success path can record it
   * without a schema migration.
   */
  "SIGNING_FAILED",
  /** Reserved for non-PDF artifacts. */
  "NOT_APPLICABLE",
] as const;
export type PdfSignatureStatus = (typeof PDF_SIGNATURE_STATUSES)[number];

export const VERIFICATION_PACKAGE_SIGNATURE_STATUSES = [
  /**
   * MANIFEST.json carries a valid Ed25519 signature
   * (MANIFEST.json.sig) and a public key (signing_key.pem) for
   * independent verification.
   */
  "SIGNED",
  /**
   * Package was emitted without a manifest signature. Should not
   * happen in current code paths — the worker always signs the
   * manifest. Reserved.
   */
  "UNSIGNED",
  /** Reserved for non-package artifacts. */
  "NOT_APPLICABLE",
] as const;
export type VerificationPackageSignatureStatus =
  (typeof VERIFICATION_PACKAGE_SIGNATURE_STATUSES)[number];

/**
 * Wire shape for the report-artifact signature block returned by
 * `GET /v1/evidence/:id/artifacts/status` and the evidence detail
 * endpoint. Designed so the frontend NEVER infers signing state from
 * a label or copy string.
 */
export type ReportPdfSignatureProjection = {
  status: PdfSignatureStatus;
  /** ISO8601 when status === "SIGNED"; null otherwise. */
  signedAtUtc: string | null;
  /**
   * Operator-facing label for the key id (e.g. "proovra_ed25519",
   * "proovra_pkcs12_2026"). NEVER the certificate or private key.
   * Null when not signed or signer key is unavailable.
   */
  signerKeyId: string | null;
  /**
   * Bounded operator-readable warning copy when the status is not
   * SIGNED. Null for SIGNED artifacts. The frontend renders this
   * verbatim — no client-side string interpolation.
   */
  warning: string | null;
};

export type VerificationPackageSignatureProjection = {
  status: VerificationPackageSignatureStatus;
  /**
   * Signer key id matching the manifest's `signing_key.pem`. NEVER
   * the certificate / private key.
   */
  signerKeyId: string | null;
};

/**
 * Convenience UI helpers. Components consume these instead of
 * hand-rolled label maps so the strings can only ever be the four
 * sanctioned variants.
 */
export const ARTIFACT_LABELS = {
  REPORT_PDF: "Report PDF",
  REPORT_PDF_SIGNED: "Signed Report PDF",
  REPORT_PDF_UNSIGNED: "Unsigned Report PDF artifact",
  VERIFICATION_PACKAGE_ZIP: "Verification Package ZIP",
  PUBLIC_VERIFY_PAGE: "Public Verify page",
} as const;

export type ArtifactLabel = (typeof ARTIFACT_LABELS)[keyof typeof ARTIFACT_LABELS];

/**
 * Bounded operator-safe warning copy for the unsigned-opt-out path.
 * Backed into the shared module so the worker (which writes it),
 * the API (which surfaces it), and the frontend (which renders it)
 * all use the same exact string. Lawyers reviewed this; do not
 * paraphrase.
 */
export const PDF_UNSIGNED_OPT_OUT_WARNING_COPY =
  "This Report PDF artifact was generated without a PDF signature. The recorded integrity state and Verification Package ZIP remain independent of this artifact's signature.";

/**
 * Bounded operator-safe warning copy for the
 * SIGNING_UNAVAILABLE path (non-production environments).
 */
export const PDF_SIGNING_UNAVAILABLE_COPY =
  "This Report PDF was generated in a non-production environment where PDF artifact signing is not configured. Production deployments require PDF artifact signing or an explicit acknowledged opt-out.";

/**
 * Vocabulary discipline — phrases the frontend must NEVER render
 * adjacent to an artifact. The Phase A2 tests grep critical files
 * for these literals.
 *
 * Why each one is forbidden:
 *   - "legally admissible" — PROOVRA records integrity, not legal
 *     status. A finder of fact determines admissibility.
 *   - "tamper-proof" — implies an absolute guarantee no system can
 *     provide. Custody is "tamper-evident" only.
 *   - "authentic" — implies authorship / factual truth.
 *   - "court-ready" — implies legal status.
 *   - "verified report" — collapses artifact signature with evidence
 *     verification state. Distinct concepts.
 *   - "legal report" — same.
 *   - "court-valid" — same.
 *   - "forensic proof" — collapses recorded integrity with absolute
 *     forensic proof.
 *   - "guaranteed" — absolute language unsupported by the system.
 */
export const FORBIDDEN_ARTIFACT_PHRASES = [
  "legally admissible",
  "tamper-proof",
  "tamper proof",
  "authentic",
  "court-ready",
  "court ready",
  "court-valid",
  "court valid",
  "verified report",
  "legal report",
  "forensic proof",
  "guaranteed",
] as const;
