-- =============================================================================
-- Phase 2.7X Stage 6 — Organization invite token hashing.
--
-- This migration introduces hashed-storage for invite tokens. The
-- raw token is generated at create-invite time and returned ONCE
-- in the response; only its SHA-256 hash is stored in the DB. Old
-- rows (pre-Stage-6) are backfilled in this migration so the
-- existing accept path continues to work without any client-side
-- change for in-flight pending invites.
--
-- Stage 6 acceptance:
--   - new invites: token column stays NULL; tokenHash holds the hash
--   - existing invites: tokenHash backfilled from raw token's SHA-256
--   - token column made NULLABLE (additive constraint relaxation)
--   - unique index on tokenHash
--
-- Subsequent stage (Stage 7 destructive cutover):
--   - UPDATE organization_invites SET token = NULL
--   - DROP COLUMN organization_invites.token
--   - DROP INDEX organization_invites_token_key
-- The Stage 7 destructive ops are out of scope here.
--
-- Phase 2.5C wrapper + Phase 2.5D in-process hook + Phase 2.5E
-- preflight + Phase 2.7X Stage 2 db:diff-guard all verified host
-- classification = LOCAL and absence of protected-table DROPs
-- before this file was applied. The migration was hand-authored
-- (not generated by `prisma migrate diff`) because the broader
-- Stage 1 schema-vs-DB drift makes `migrate diff` propose
-- unfiltered destructive ops on the 13 drift-catalog tables.
-- Hand-authoring this minimal additive file keeps it surgical.
-- =============================================================================

-- pgcrypto provides digest() for the backfill. Most Postgres
-- installations already enable it; the `IF NOT EXISTS` makes the
-- migration idempotent across environments.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Step 1 — add the column (nullable; populated by Step 2).
ALTER TABLE "organization_invites" ADD COLUMN "token_hash" VARCHAR(64);

-- Step 2 — backfill tokenHash from the existing raw token. We
-- read the raw value, compute SHA-256, hex-encode (64 chars), and
-- write it back into the new column. This is the ONLY place the
-- raw token is read out of the database; the code path that
-- generated it is the only other touch point.
UPDATE "organization_invites"
SET "token_hash" = encode(digest("token", 'sha256'), 'hex')
WHERE "token" IS NOT NULL;

-- Step 3 — tighten the new column to NOT NULL now that all rows
-- are populated. Risk-scan flags this as WARNING (ALTER COLUMN
-- SET NOT NULL); this is the documented exception per the
-- Stage 6 readiness doc.
ALTER TABLE "organization_invites" ALTER COLUMN "token_hash" SET NOT NULL;

-- Step 4 — relax the raw token's NOT NULL constraint. New rows
-- write NULL for `token` (Stage 6 code path) while existing rows
-- retain their value for rollback compat. The UNIQUE index on
-- `token` remains; PostgreSQL allows multiple NULLs in a UNIQUE
-- column, so this does not constrain new inserts.
ALTER TABLE "organization_invites" ALTER COLUMN "token" DROP NOT NULL;

-- Step 5 — unique index on token_hash. Operators looking up an
-- invite by its hash get O(log n) index probe.
CREATE UNIQUE INDEX "organization_invites_token_hash_key" ON "organization_invites"("token_hash");
