/**
 * PHASE 0 §1 — WORKING-TREE FREEZE AND RECOVERY MANIFEST.
 *
 * Why this is a script and not a table in a report
 * ---------------------------------------------------------------------------
 * §1 requires counters to be ZERO: UnknownChangedPaths, SensitiveForbiddenPaths,
 * HistoricalMigrationsModified. A hand-written table cannot prove a zero,
 * because a path added after the table was written is simply absent from it.
 * This collector re-reads `git status` on every run, so the zero is re-derived
 * rather than remembered.
 *
 * It classifies by PATH SHAPE only, and every rule carries the reason it is
 * safe. A path that matches no rule is UNKNOWN — deliberately, so that a new
 * kind of file fails the gate instead of being silently swept into a bucket.
 *
 * It also records the SHA-256 of every CHANGED audit-related file, which is
 * what makes the manifest a RECOVERY record: a deletion made during
 * consolidation can be checked against the digest it had before, so "recoverable
 * from Git" is a verifiable claim rather than an assurance.
 *
 * It prints and stores NAMES AND DIGESTS ONLY. File contents never leave this
 * module, so no secret can transit it.
 *
 * PHASE 0 NOTE. This began as `audit-output/phase12-final-remediation/freeze/
 * classify-working-tree.mjs` — a collector living inside the directory it wrote
 * to, with no consumer and no command. It is now a component of the canonical
 * engine, driven by `pnpm audit:architecture`.
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";

import { REPO, RECOVERY_SCHEMA_VERSION } from "./registry.mjs";

const git = (...args) =>
  execFileSync("git", args, { cwd: REPO, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });

/**
 * Classification rules, evaluated in order. First match wins.
 *
 * `class` is one of the eight §1 categories. `why` is the argument that the
 * rule is sound — it is carried into the artifact so a reader can dispute the
 * classification without re-deriving it.
 */
const RULES = [
  {
    class: "SENSITIVE_FORBIDDEN",
    why: "Anything shaped like a credential, key or environment file must never be a tracked change in a release candidate.",
    test: (p) =>
      /(^|\/)\.env($|\.)/i.test(p) ||
      /\.(pem|p12|pfx|key|keystore|jks)$/i.test(p) ||
      /(^|\/)(id_rsa|id_ed25519)($|\.)/i.test(p) ||
      /(^|\/)(secrets?|credentials?)\.(json|ya?ml|txt)$/i.test(p),
  },
  {
    class: "REGENERABLE_TEMP",
    why: "Recovery/scratch residue that a later run reproduces from source; carries no authority.",
    test: (p) =>
      p.startsWith(".p12snapshot/") ||
      /(^|\/)(node_modules|\.next|dist|coverage|\.turbo|\.tmp)\//.test(p) ||
      /\.(log|tmp|bak|orig|rej)$/i.test(p),
  },
  {
    class: "TEST_OR_GUARD",
    why: "Executable evidence: a suite or a regression guard. Never the product authority (§0 rule 15).",
    test: (p) =>
      /(^|\/)(test|tests|__tests__)\//.test(p) ||
      p.startsWith("e2e/") ||
      /\.(test|spec)\.(ts|tsx|mjs|js)$/.test(p),
  },
  {
    class: "REQUIRED_NEW_TOOLING",
    why: "A verifier, collector or generator that computes a counter the audit depends on.",
    test: (p) => /(^|\/)scripts\//.test(p) || /(^|\/)tools\//.test(p),
  },
  {
    class: "PROOF_ARTIFACT",
    why: "Machine-written record of what actually executed; regenerated by its runner, never hand-edited.",
    test: (p) =>
      p.startsWith("audit-output/") ||
      /^docs\/architecture\/.*\.json$/.test(p),
  },
  {
    class: "DOCUMENTATION",
    why: "Prose. Changes no runtime behaviour.",
    test: (p) => /\.(md|mdx|txt)$/i.test(p) || p.startsWith("docs/"),
  },
  {
    class: "PRODUCTION_SOURCE",
    why: "Ships to users: application source, package manifests, schema, infrastructure definitions.",
    test: (p) =>
      /^(services|apps|packages|mobile)\/.*\.(ts|tsx|js|jsx|mjs|cjs|css|scss|json|prisma|sql)$/.test(p) ||
      /^(Dockerfile|docker-compose)/.test(p) ||
      /(^|\/)(Dockerfile|docker-compose[^/]*\.ya?ml)$/.test(p) ||
      /^\.github\/workflows\//.test(p),
  },
  {
    class: "PRODUCTION_SOURCE",
    why:
      "Repository-root release configuration. It does not itself execute in production, but it DETERMINES WHAT THE RELEASE CONTAINS (.gitignore/.dockerignore), how it is compiled (tsconfig), or what the workspace resolves and runs (package.json / the lockfile / pnpm-workspace.yaml), so a change here is a change to the shipped artifact and must be reviewed as source rather than filed as documentation.",
    test: (p) =>
      /^\.(gitignore|dockerignore|gitattributes|npmrc|nvmrc)$/.test(p) ||
      /^tsconfig(\.[\w.-]+)?\.json$/.test(p) ||
      /^(package\.json|package-lock\.json|pnpm-lock\.yaml|pnpm-workspace\.yaml|turbo\.json)$/.test(p),
  },
];

function classify(path) {
  for (const rule of RULES) {
    if (rule.test(path)) return { class: rule.class, why: rule.why };
  }
  return { class: "UNKNOWN", why: "Matched no classification rule." };
}

export function evaluate() {
  const porcelain = git("status", "--porcelain").split("\n").filter(Boolean);

  const entries = porcelain.map((line) => {
    const index = line[0];
    const worktree = line[1];
    let path = line.slice(3).trim();
    // Rename/copy entries are "old -> new"; the new path is the one that ships.
    if (path.includes(" -> ")) path = path.split(" -> ")[1];
    if (path.startsWith('"') && path.endsWith('"')) path = path.slice(1, -1);
    const change =
      index === "?" ? "UNTRACKED" : index !== " " ? `STAGED_${index}` : `WORKTREE_${worktree}`;
    return { path, change, ...classify(path) };
  });

  const byClass = {};
  for (const e of entries) (byClass[e.class] ??= []).push(e.path);

  const head = git("rev-parse", "HEAD").trim();
  const branch = git("rev-parse", "--abbrev-ref", "HEAD").trim();
  let upstream = null;
  let ahead = null;
  let behind = null;
  try {
    upstream = git("rev-parse", "origin/main").trim();
    const [b, a] = git("rev-list", "--left-right", "--count", "origin/main...HEAD")
      .trim()
      .split(/\s+/)
      .map(Number);
    behind = b;
    ahead = a;
  } catch {
    /* no remote configured — recorded as null, never guessed */
  }

  // A HISTORICAL migration is one that exists in HEAD. Adding a NEW migration
  // directory is permitted; editing a committed one is the §0 rule-3 violation.
  const tracked = new Set(git("ls-files").split("\n").filter(Boolean));
  const historicalMigrationsModified = entries
    .filter((e) => /(^|\/)migrations\//.test(e.path))
    .filter((e) => e.change !== "UNTRACKED" && tracked.has(e.path))
    .map((e) => e.path);

  // SHA-256 of every CHANGED audit-related file that still exists on disk.
  // A deleted path carries `null` — the digest of a file that is gone is
  // recorded by Git, not invented here.
  const AUDIT_SHAPED =
    /(audit|verify|gate|ledger|capabilit|closure|reconcil|proof|reachab|authority|governance)/i;
  const auditDigests = entries
    .filter((e) => AUDIT_SHAPED.test(e.path) || e.path.startsWith("audit-output/"))
    .map((e) => {
      const abs = join(REPO, e.path);
      let sha = null;
      try {
        if (existsSync(abs) && statSync(abs).isFile()) {
          sha = createHash("sha256").update(readFileSync(abs)).digest("hex");
        }
      } catch {
        sha = null;
      }
      return { path: e.path, change: e.change, sha256: sha };
    });

  return {
    schemaVersion: RECOVERY_SCHEMA_VERSION,
    generatedBy: "services/api/scripts/audit/engine/worktree.mjs",
    frozenAtUtc: new Date().toISOString(),
    note: "Every count below is derived from `git status` at run time. No count is hand-maintained. Names and digests only — no file contents.",
    branch,
    head,
    originMain: upstream,
    ahead,
    behind,
    changedPathCount: entries.length,
    entries,
    byClassCounts: Object.fromEntries(
      Object.entries(byClass).map(([k, v]) => [k, v.length]),
    ),
    byClass,
    auditRelatedChangedFiles: auditDigests,
    counters: {
      UnknownChangedPaths: (byClass.UNKNOWN ?? []).length,
      SensitiveForbiddenPaths: (byClass.SENSITIVE_FORBIDDEN ?? []).length,
      HistoricalMigrationsModified: historicalMigrationsModified.length,
      AuditRelatedChangedFiles: auditDigests.length,
    },
    historicalMigrationsModified,
  };
}
