export const REPORT_BRAND = {
  name: "PROOVRA",
  reportTitle: "Verification Report",
  tagline: "Capture truth. Prove it forever.",
  colors: {
    ink: "#101828",
    muted: "#475467",
    subtle: "#667085",
    line: "#D0D5DD",
    softLine: "#EAECF0",
    paper: "#F8FAFC",
    white: "#FFFFFF",
    accent: "#153B67",
    accentSoft: "#EAF2FA",
    success: "#0F6B4F",
    successSoft: "#ECFDF3",
    warning: "#9A6700",
    warningSoft: "#FFFAEB",
    danger: "#B42318",
    dangerSoft: "#FEF3F2",
    neutralSoft: "#F5F7FA",
  },
  spacing: {
    pageMaxWidth: 980,
    sectionGap: 28,
    cardRadius: 16,
    blockRadius: 12,
  },
} as const;