-- =============================================================================
-- Phase 0 schema catchup migration
-- =============================================================================
--
-- Auto-generated by `prisma migrate diff --from-config-datasource
-- --to-schema schema.prisma --script` on 2026-05-26 against a DB that
-- already has the canonical 84 migrations + the new corrective
-- migration 20260417000000_create_verification_source_enum.
--
-- It closes the drift between what the canonical migration chain
-- creates and what schema.prisma declares the application expects.
-- Without this migration the Prisma client raises P2022 at runtime
-- (e.g. "column users.avatar_url does not exist") — the runtime
-- validator does not catch these because they are below its
-- catalog granularity (per-column-by-column is not exhaustive in
-- the catalog).
--
-- Idempotency:
--   * ADD COLUMN  wrapped in IF NOT EXISTS
--   * ALTER TYPE ADD VALUE wrapped in IF NOT EXISTS (Postgres 12+)
--   * CREATE TABLE / CREATE [UNIQUE] INDEX use IF NOT EXISTS
--   * ALTER INDEX RENAME wrapped in DO blocks that check both
--     existence of source and absence of target.
--   * mfa_recovery_request_status enum recreation block stripped
--     (cosmetic; the enum is already correct on every environment).
--
-- For environments that ALREADY have these objects (production after
-- drift-patches), this migration is a no-op and Prisma records it
-- in `_prisma_migrations` history.
-- =============================================================================

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'EVIDENCE_COMPLETED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'TIMESTAMP_APPLIED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'TIMESTAMP_FAILED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'VERIFICATION_PACKAGE_GENERATED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'VERIFICATION_PACKAGE_DOWNLOADED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'TECHNICAL_VERIFICATION_CHECKED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'REVIEW_READY';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'CERTIFICATION_REQUESTED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'CERTIFICATION_ATTESTED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'CERTIFICATION_REVOKED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'IDENTITY_SNAPSHOT_RECORDED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'ANCHOR_PUBLISHED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'ANCHOR_FAILED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'OTS_APPLIED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'OTS_FAILED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'EVIDENCE_DELETE_SCHEDULED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'EVIDENCE_DELETE_RESTORED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'EVIDENCE_PURGED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'EVIDENCE_ARCHIVED';
ALTER TYPE "CustodyEventType" ADD VALUE IF NOT EXISTS 'EVIDENCE_RESTORED';

-- AlterEnum
-- (skipped) mfa_recovery_request_status enum recreation
-- The enum is already correct on every environment. The Prisma diff
-- attempted a cosmetic type rename that would fail on re-run.

-- DropForeignKey
ALTER TABLE "access_reviews" DROP CONSTRAINT "access_reviews_completed_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "access_reviews" DROP CONSTRAINT "access_reviews_initiated_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "access_reviews" DROP CONSTRAINT "access_reviews_subject_user_id_fkey";

-- DropForeignKey
ALTER TABLE "access_reviews" DROP CONSTRAINT "access_reviews_team_id_fkey";

-- DropForeignKey
ALTER TABLE "api_credentials" DROP CONSTRAINT "api_credentials_disabled_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "authenticated_sessions" DROP CONSTRAINT "authenticated_sessions_team_id_fkey";

-- DropForeignKey
ALTER TABLE "authenticated_sessions" DROP CONSTRAINT "authenticated_sessions_user_id_fkey";

-- DropForeignKey
ALTER TABLE "case_access" DROP CONSTRAINT "case_access_case_id_fkey";

-- DropForeignKey
ALTER TABLE "communication_messages" DROP CONSTRAINT "communication_messages_created_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "communication_messages" DROP CONSTRAINT "communication_messages_related_discussion_thread_id_fkey";

-- DropForeignKey
ALTER TABLE "communication_messages" DROP CONSTRAINT "communication_messages_related_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "communication_messages" DROP CONSTRAINT "communication_messages_related_evidence_request_id_fkey";

-- DropForeignKey
ALTER TABLE "communication_messages" DROP CONSTRAINT "communication_messages_related_intake_session_id_fkey";

-- DropForeignKey
ALTER TABLE "communication_messages" DROP CONSTRAINT "communication_messages_team_id_fkey";

-- DropForeignKey
ALTER TABLE "communication_preferences" DROP CONSTRAINT "communication_preferences_team_id_fkey";

-- DropForeignKey
ALTER TABLE "communication_preferences" DROP CONSTRAINT "communication_preferences_user_id_fkey";

-- DropForeignKey
ALTER TABLE "destruction_executions" DROP CONSTRAINT "destruction_executions_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "destruction_executions" DROP CONSTRAINT "destruction_executions_executed_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "destruction_executions" DROP CONSTRAINT "destruction_executions_review_id_fkey";

-- DropForeignKey
ALTER TABLE "destruction_executions" DROP CONSTRAINT "destruction_executions_team_id_fkey";

-- DropForeignKey
ALTER TABLE "destruction_reviews" DROP CONSTRAINT "destruction_reviews_decided_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "destruction_reviews" DROP CONSTRAINT "destruction_reviews_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "destruction_reviews" DROP CONSTRAINT "destruction_reviews_initiated_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "destruction_reviews" DROP CONSTRAINT "destruction_reviews_team_id_fkey";

-- DropForeignKey
ALTER TABLE "entitlements" DROP CONSTRAINT "entitlements_user_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_lifecycle_events" DROP CONSTRAINT "evidence_lifecycle_events_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_lifecycle_events" DROP CONSTRAINT "evidence_lifecycle_events_team_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_parts" DROP CONSTRAINT "evidence_parts_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_retention_policies" DROP CONSTRAINT "evidence_retention_policies_created_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_retention_policies" DROP CONSTRAINT "evidence_retention_policies_team_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_retention_policy_versions" DROP CONSTRAINT "evidence_retention_policy_versions_authored_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_retention_policy_versions" DROP CONSTRAINT "evidence_retention_policy_versions_policy_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_saved_views" DROP CONSTRAINT "evidence_saved_views_team_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_search_documents" DROP CONSTRAINT "evidence_search_documents_team_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_upload_session_parts" DROP CONSTRAINT "evidence_upload_session_parts_session_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_instance_evidence" DROP CONSTRAINT "evidence_workflow_instance_evidence_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_instance_evidence" DROP CONSTRAINT "evidence_workflow_instance_evidence_workflow_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_instances" DROP CONSTRAINT "evidence_workflow_instances_assigned_reviewer_user_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_instances" DROP CONSTRAINT "evidence_workflow_instances_created_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_instances" DROP CONSTRAINT "evidence_workflow_instances_evidence_request_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_instances" DROP CONSTRAINT "evidence_workflow_instances_intake_session_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_instances" DROP CONSTRAINT "evidence_workflow_instances_team_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_instances" DROP CONSTRAINT "evidence_workflow_instances_template_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_step_instances" DROP CONSTRAINT "evidence_workflow_step_instances_completed_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_step_instances" DROP CONSTRAINT "evidence_workflow_step_instances_mapped_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_step_instances" DROP CONSTRAINT "evidence_workflow_step_instances_workflow_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_visibility_decisions" DROP CONSTRAINT "evidence_workflow_visibility_decisions_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "evidence_workflow_visibility_decisions" DROP CONSTRAINT "evidence_workflow_visibility_decisions_workflow_id_fkey";

-- DropForeignKey
ALTER TABLE "external_identity_mappings" DROP CONSTRAINT "external_identity_mappings_team_id_fkey";

-- DropForeignKey
ALTER TABLE "external_identity_mappings" DROP CONSTRAINT "external_identity_mappings_user_id_fkey";

-- DropForeignKey
ALTER TABLE "governance_export_snapshots" DROP CONSTRAINT "governance_export_snapshots_created_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "governance_export_snapshots" DROP CONSTRAINT "governance_export_snapshots_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "governance_export_snapshots" DROP CONSTRAINT "governance_export_snapshots_team_id_fkey";

-- DropForeignKey
ALTER TABLE "governance_notifications" DROP CONSTRAINT "governance_notifications_related_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "governance_notifications" DROP CONSTRAINT "governance_notifications_team_id_fkey";

-- DropForeignKey
ALTER TABLE "governance_reconciliation_runs" DROP CONSTRAINT "governance_reconciliation_runs_team_id_fkey";

-- DropForeignKey
ALTER TABLE "governance_reconciliation_runs" DROP CONSTRAINT "governance_reconciliation_runs_triggered_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "guest_identities" DROP CONSTRAINT "guest_identities_claimed_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "guest_identities" DROP CONSTRAINT "guest_identities_user_id_fkey";

-- DropForeignKey
ALTER TABLE "immutable_storage_checks" DROP CONSTRAINT "immutable_storage_checks_evidence_id_fkey";

-- DropForeignKey
ALTER TABLE "immutable_storage_checks" DROP CONSTRAINT "immutable_storage_checks_team_id_fkey";

-- DropForeignKey
ALTER TABLE "investigation_graph_edges" DROP CONSTRAINT "investigation_graph_edges_source_node_id_fkey";

-- DropForeignKey
ALTER TABLE "investigation_graph_edges" DROP CONSTRAINT "investigation_graph_edges_target_node_id_fkey";

-- DropForeignKey
ALTER TABLE "manual_relationships" DROP CONSTRAINT "manual_relationships_source_node_id_fkey";

-- DropForeignKey
ALTER TABLE "manual_relationships" DROP CONSTRAINT "manual_relationships_target_node_id_fkey";

-- DropForeignKey
ALTER TABLE "member_capability_grants" DROP CONSTRAINT "member_capability_grants_granted_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "member_capability_grants" DROP CONSTRAINT "member_capability_grants_revoked_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "member_capability_grants" DROP CONSTRAINT "member_capability_grants_team_id_fkey";

-- DropForeignKey
ALTER TABLE "member_capability_grants" DROP CONSTRAINT "member_capability_grants_team_member_id_fkey";

-- DropForeignKey
ALTER TABLE "member_delegated_admin_scopes" DROP CONSTRAINT "member_delegated_admin_scopes_granted_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "member_delegated_admin_scopes" DROP CONSTRAINT "member_delegated_admin_scopes_revoked_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "member_delegated_admin_scopes" DROP CONSTRAINT "member_delegated_admin_scopes_team_id_fkey";

-- DropForeignKey
ALTER TABLE "member_delegated_admin_scopes" DROP CONSTRAINT "member_delegated_admin_scopes_team_member_id_fkey";

-- DropForeignKey
ALTER TABLE "operational_incident_events" DROP CONSTRAINT "operational_incident_events_incident_id_fkey";

-- DropForeignKey
ALTER TABLE "operational_incidents" DROP CONSTRAINT "operational_incidents_acknowledged_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "operational_incidents" DROP CONSTRAINT "operational_incidents_resolved_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "operational_incidents" DROP CONSTRAINT "operational_incidents_team_id_fkey";

-- DropForeignKey
ALTER TABLE "organization_security_policies" DROP CONSTRAINT "organization_security_policies_team_id_fkey";

-- DropForeignKey
ALTER TABLE "organization_security_policies" DROP CONSTRAINT "organization_security_policies_updated_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "password_reset_tokens_user_id_fkey";

-- DropForeignKey
ALTER TABLE "payments" DROP CONSTRAINT "payments_user_id_fkey";

-- DropForeignKey
ALTER TABLE "review_escalations" DROP CONSTRAINT "review_escalations_acknowledged_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "review_escalations" DROP CONSTRAINT "review_escalations_assigned_to_user_id_fkey";

-- DropForeignKey
ALTER TABLE "review_escalations" DROP CONSTRAINT "review_escalations_created_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "review_escalations" DROP CONSTRAINT "review_escalations_resolved_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "review_escalations" DROP CONSTRAINT "review_escalations_team_id_fkey";

-- DropForeignKey
ALTER TABLE "review_escalations" DROP CONSTRAINT "review_escalations_workflow_id_fkey";

-- DropForeignKey
ALTER TABLE "reviewer_ops_reminders" DROP CONSTRAINT "reviewer_ops_reminders_team_id_fkey";

-- DropForeignKey
ALTER TABLE "reviewer_workload_snapshots" DROP CONSTRAINT "reviewer_workload_snapshots_reviewer_user_id_fkey";

-- DropForeignKey
ALTER TABLE "reviewer_workload_snapshots" DROP CONSTRAINT "reviewer_workload_snapshots_team_id_fkey";

-- DropForeignKey
ALTER TABLE "revoked_sessions" DROP CONSTRAINT "revoked_sessions_revoked_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "revoked_sessions" DROP CONSTRAINT "revoked_sessions_team_id_fkey";

-- DropForeignKey
ALTER TABLE "revoked_sessions" DROP CONSTRAINT "revoked_sessions_user_id_fkey";

-- DropForeignKey
ALTER TABLE "risk_signals" DROP CONSTRAINT "risk_signals_subject_user_id_fkey";

-- DropForeignKey
ALTER TABLE "risk_signals" DROP CONSTRAINT "risk_signals_team_id_fkey";

-- DropForeignKey
ALTER TABLE "saved_search_views" DROP CONSTRAINT "saved_search_views_created_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "saved_search_views" DROP CONSTRAINT "saved_search_views_team_id_fkey";

-- DropForeignKey
ALTER TABLE "scim_groups" DROP CONSTRAINT "scim_groups_team_id_fkey";

-- DropForeignKey
ALTER TABLE "scim_provisioning_tokens" DROP CONSTRAINT "scim_provisioning_tokens_created_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "scim_provisioning_tokens" DROP CONSTRAINT "scim_provisioning_tokens_team_id_fkey";

-- DropForeignKey
ALTER TABLE "sso_callback_attempts" DROP CONSTRAINT "sso_callback_attempts_sso_connection_id_fkey";

-- DropForeignKey
ALTER TABLE "sso_callback_attempts" DROP CONSTRAINT "sso_callback_attempts_team_id_fkey";

-- DropForeignKey
ALTER TABLE "sso_connections" DROP CONSTRAINT "sso_connections_created_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "sso_connections" DROP CONSTRAINT "sso_connections_team_id_fkey";

-- DropForeignKey
ALTER TABLE "step_up_challenges" DROP CONSTRAINT "step_up_challenges_initiated_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "step_up_challenges" DROP CONSTRAINT "step_up_challenges_team_id_fkey";

-- DropForeignKey
ALTER TABLE "subscriptions" DROP CONSTRAINT "subscriptions_user_id_fkey";

-- DropForeignKey
ALTER TABLE "team_invites" DROP CONSTRAINT "team_invites_team_id_fkey";

-- DropForeignKey
ALTER TABLE "team_members" DROP CONSTRAINT "team_members_access_granted_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "team_members" DROP CONSTRAINT "team_members_revoked_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "team_members" DROP CONSTRAINT "team_members_suspended_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "team_members" DROP CONSTRAINT "team_members_team_id_fkey";

-- DropForeignKey
ALTER TABLE "team_members" DROP CONSTRAINT "team_members_user_id_fkey";

-- DropForeignKey
ALTER TABLE "trusted_devices" DROP CONSTRAINT "trusted_devices_revoked_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "trusted_devices" DROP CONSTRAINT "trusted_devices_team_id_fkey";

-- DropForeignKey
ALTER TABLE "trusted_devices" DROP CONSTRAINT "trusted_devices_user_id_fkey";

-- DropForeignKey
ALTER TABLE "verification_attempts" DROP CONSTRAINT "verification_attempts_initiated_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "verification_attempts" DROP CONSTRAINT "verification_attempts_team_id_fkey";

-- DropForeignKey
ALTER TABLE "workflow_intake_sessions" DROP CONSTRAINT "workflow_intake_sessions_revoked_by_user_id_fkey";

-- DropForeignKey
ALTER TABLE "workspace_persona_profiles" DROP CONSTRAINT "workspace_persona_profiles_team_id_fkey";

-- AlterTable
ALTER TABLE "access_anomalies" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "access_reviews" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "api_credentials" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "automation_rules" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "automation_webhook_deliveries" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "automation_webhook_destinations" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "capture_sessions" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "case_assignments" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "case_comments" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "case_evidence_links" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "case_legal_holds" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "case_status_history" DROP COLUMN "from_status",
DROP COLUMN "to_status",
ADD COLUMN IF NOT EXISTS "fromStatus" "CaseStatus",
ADD COLUMN IF NOT EXISTS "toStatus" "CaseStatus" NOT NULL;

-- AlterTable
ALTER TABLE "cases" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "communication_messages" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "communication_preferences" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "cookie_consent_records" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "custody_events" ADD COLUMN IF NOT EXISTS "event_hash" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "prev_event_hash" VARCHAR(64);

-- AlterTable
ALTER TABLE "destruction_reviews" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "discussion_threads" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "entitlements" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence" ADD COLUMN IF NOT EXISTS "capture_method" "CaptureMethod",
ADD COLUMN IF NOT EXISTS "created_by_user_id" UUID,
ADD COLUMN IF NOT EXISTS "delete_scheduled_for_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "deleted_by_user_id" UUID,
ADD COLUMN IF NOT EXISTS "display_file_name" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "identity_level_snapshot" "IdentityLevel",
ADD COLUMN IF NOT EXISTS "last_accessed_at_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "last_accessed_by_user_id" UUID,
ADD COLUMN IF NOT EXISTS "last_verified_at_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "last_verified_source" "VerificationSource",
ADD COLUMN IF NOT EXISTS "latest_report_version" INTEGER,
ADD COLUMN IF NOT EXISTS "organization_name_snapshot" VARCHAR(180),
ADD COLUMN IF NOT EXISTS "organization_verified_snapshot" BOOLEAN,
ADD COLUMN IF NOT EXISTS "original_file_name" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "ots_anchored_at_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "ots_bitcoin_txid" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "ots_calendar" VARCHAR(512),
ADD COLUMN IF NOT EXISTS "ots_failure_reason" TEXT,
ADD COLUMN IF NOT EXISTS "ots_hash" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "ots_proof_base64" TEXT,
ADD COLUMN IF NOT EXISTS "ots_status" VARCHAR(32),
ADD COLUMN IF NOT EXISTS "ots_upgraded_at_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "recorded_integrity_verified_at_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "review_ready_at_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "reviewer_summary_version" INTEGER,
ADD COLUMN IF NOT EXISTS "storage_object_lock_legal_hold_status" VARCHAR(16),
ADD COLUMN IF NOT EXISTS "storage_object_lock_mode" VARCHAR(32),
ADD COLUMN IF NOT EXISTS "storage_object_lock_retain_until_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "storage_region" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "submitted_by_auth_provider" "AuthProvider",
ADD COLUMN IF NOT EXISTS "submitted_by_email" VARCHAR(320),
ADD COLUMN IF NOT EXISTS "submitted_by_user_id" UUID,
ADD COLUMN IF NOT EXISTS "title" VARCHAR(160),
ADD COLUMN IF NOT EXISTS "uploaded_by_user_id" UUID,
ADD COLUMN IF NOT EXISTS "verification_package_generated_at_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "verification_package_metadata" JSONB,
ADD COLUMN IF NOT EXISTS "verification_package_version" INTEGER,
ADD COLUMN IF NOT EXISTS "verification_status" "VerificationStatus",
ADD COLUMN IF NOT EXISTS "workspace_name_snapshot" VARCHAR(180),
ALTER COLUMN "signature_base64" SET DATA TYPE VARCHAR(4096),
DROP COLUMN "locked_by_user_id",
ADD COLUMN IF NOT EXISTS "locked_by_user_id" UUID;

-- AlterTable
ALTER TABLE "evidence_ai_categorizations" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_annotations" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_extracted_texts" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_integrity_snapshots" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_intelligence_jobs" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_legal_holds" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_legal_notes" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_parts" ADD COLUMN IF NOT EXISTS "original_file_name" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "storage_object_lock_legal_hold_status" VARCHAR(16),
ADD COLUMN IF NOT EXISTS "storage_object_lock_mode" VARCHAR(32),
ADD COLUMN IF NOT EXISTS "storage_object_lock_retain_until_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "storage_region" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "uploaded_at_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "uploaded_by_user_id" UUID;

-- AlterTable
ALTER TABLE "evidence_relationships" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_request_deliverables" ALTER COLUMN "accepted_kinds" DROP DEFAULT,
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_request_responses" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_requests" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_retention_policies" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_review_workflows" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_reviewer_comments" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_saved_views" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_search_documents" DROP COLUMN "tsv",
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_workflow_instances" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_workflow_step_instances" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_workflow_templates" ALTER COLUMN "intake_modes" DROP DEFAULT,
ALTER COLUMN "allowed_roles" DROP DEFAULT,
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "evidence_workflow_visibility_decisions" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "external_identity_mappings" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "file_security_scans" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "integration_webhook_deliveries" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "integration_webhook_endpoints" DROP COLUMN "event_types",
ADD COLUMN IF NOT EXISTS "eventTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "member_capability_grants" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "member_delegated_admin_scopes" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "notification_deliveries" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "operational_causality_chains" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "operational_correlations" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "operational_graph_nodes" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "operational_incidents" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "operational_workflows" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "organization_security_policies" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "team_id" UUID;

-- AlterTable
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "capture_method_snapshot" "CaptureMethod",
ADD COLUMN IF NOT EXISTS "identity_level_snapshot" "IdentityLevel",
ADD COLUMN IF NOT EXISTS "size_bytes" BIGINT,
ADD COLUMN IF NOT EXISTS "storage_object_lock_legal_hold_status" VARCHAR(16),
ADD COLUMN IF NOT EXISTS "storage_object_lock_mode" VARCHAR(32),
ADD COLUMN IF NOT EXISTS "storage_object_lock_retain_until_utc" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "storage_region" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "submitted_by_auth_provider_snapshot" "AuthProvider",
ADD COLUMN IF NOT EXISTS "submitted_by_email_snapshot" VARCHAR(320),
ADD COLUMN IF NOT EXISTS "trust_decision_snapshot" JSONB,
ADD COLUMN IF NOT EXISTS "verification_status_snapshot" "VerificationStatus";

-- AlterTable
ALTER TABLE "review_escalations" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "reviewer_routing_recommendations" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "saved_search_views" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "scim_groups" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "scim_provisioning_tokens" ALTER COLUMN "scopes" DROP DEFAULT,
ALTER COLUMN "ip_allowlist" DROP DEFAULT,
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "security_events" DROP COLUMN "api_credential_id",
DROP COLUMN "created_at",
DROP COLUMN "details",
DROP COLUMN "event_type",
DROP COLUMN "evidence_id",
DROP COLUMN "team_id",
DROP COLUMN "webhook_endpoint_id",
ADD COLUMN IF NOT EXISTS "createdAtUtc" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "eventType" VARCHAR(64) NOT NULL,
ADD COLUMN IF NOT EXISTS "ipAddressHash" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "metadataJson" JSONB,
ADD COLUMN IF NOT EXISTS "requestId" VARCHAR(80),
ADD COLUMN IF NOT EXISTS "teamId" UUID,
ADD COLUMN IF NOT EXISTS "userAgent" VARCHAR(512),
ADD COLUMN IF NOT EXISTS "userId" UUID;

-- AlterTable
ALTER TABLE "sso_callback_attempts" ADD COLUMN IF NOT EXISTS "saml_authn_request_id" VARCHAR(128);

-- AlterTable
ALTER TABLE "sso_connections" ADD COLUMN IF NOT EXISTS "saml_attribute_mapping" JSONB,
ADD COLUMN IF NOT EXISTS "saml_cert_fingerprint" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "saml_cert_next_fingerprint" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "saml_cert_next_not_after" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "saml_cert_not_after" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "saml_certificate" TEXT,
ADD COLUMN IF NOT EXISTS "saml_certificate_next" TEXT,
ADD COLUMN IF NOT EXISTS "saml_entity_id" VARCHAR(400),
ADD COLUMN IF NOT EXISTS "saml_idp_entity_id" VARCHAR(400),
ADD COLUMN IF NOT EXISTS "saml_last_test_error" VARCHAR(128),
ADD COLUMN IF NOT EXISTS "saml_last_test_status" VARCHAR(16),
ADD COLUMN IF NOT EXISTS "saml_last_tested_at" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "saml_name_id_format" VARCHAR(200),
ADD COLUMN IF NOT EXISTS "saml_scim_managed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "saml_sign_requests" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "saml_sso_url" VARCHAR(400),
ALTER COLUMN "allowed_email_domains" DROP DEFAULT,
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "step_up_challenges" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "team_id" UUID,
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "billing_activated_at" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "billing_canceled_at" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "billing_owner_user_id" UUID,
ADD COLUMN IF NOT EXISTS "evidence_workspace_label" VARCHAR(180),
ADD COLUMN IF NOT EXISTS "storage_bytes_override" BIGINT,
ADD COLUMN IF NOT EXISTS "verification_state" "OrganizationVerificationState",
ADD COLUMN IF NOT EXISTS "verified_at_utc" TIMESTAMPTZ(6),
DROP COLUMN "owner_user_id",
ADD COLUMN IF NOT EXISTS "owner_user_id" UUID NOT NULL,
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "trusted_devices" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "upload_sessions" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "avatar_url" VARCHAR(512),
ADD COLUMN IF NOT EXISTS "bio" VARCHAR(280),
ADD COLUMN IF NOT EXISTS "current_workspace_id" UUID,
ADD COLUMN IF NOT EXISTS "email_verified_at" TIMESTAMPTZ(6),
ADD COLUMN IF NOT EXISTS "first_name" VARCHAR(80),
ADD COLUMN IF NOT EXISTS "last_name" VARCHAR(80),
ADD COLUMN IF NOT EXISTS "locale" VARCHAR(12),
ADD COLUMN IF NOT EXISTS "organization_verification_state" "OrganizationVerificationState",
ADD COLUMN IF NOT EXISTS "timezone" VARCHAR(64),
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "verification_attempts" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "workflow_intake_links" ALTER COLUMN "allowed_accepted_kinds" DROP DEFAULT,
ALTER COLUMN "ip_allowlist_cidrs" DROP DEFAULT,
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "workflow_intake_sessions" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "workspace_governance_policies" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "workspace_persona_profiles" ALTER COLUMN "updated_at" DROP DEFAULT;

-- CreateTable
CREATE TABLE IF NOT EXISTS "evidence_anchors" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "evidence_id" UUID NOT NULL,
    "provider" VARCHAR(64) NOT NULL,
    "mode" VARCHAR(32) NOT NULL,
    "anchor_hash" VARCHAR(64) NOT NULL,
    "receipt_id" VARCHAR(255),
    "transaction_id" VARCHAR(255),
    "public_url" VARCHAR(1024),
    "anchored_at_utc" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "evidence_anchors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "evidence_certifications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "evidence_id" UUID NOT NULL,
    "declaration_type" "CertificationType" NOT NULL,
    "status" "CertificationStatus" NOT NULL DEFAULT 'DRAFT',
    "version" INTEGER NOT NULL DEFAULT 1,
    "requested_by_user_id" UUID,
    "requested_at_utc" TIMESTAMPTZ(6),
    "attested_by_user_id" UUID,
    "attested_at_utc" TIMESTAMPTZ(6),
    "attestor_name" VARCHAR(160),
    "attestor_title" VARCHAR(160),
    "attestor_email" VARCHAR(320),
    "attestor_organization" VARCHAR(180),
    "statement_markdown" TEXT,
    "statement_snapshot" JSONB,
    "signature_text" VARCHAR(512),
    "certification_hash" VARCHAR(64),
    "revoked_at_utc" TIMESTAMPTZ(6),
    "revoked_by_user_id" UUID,
    "revoke_reason" VARCHAR(500),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "evidence_certifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "verification_packages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "evidence_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "storage_bucket" VARCHAR(255) NOT NULL,
    "storage_key" VARCHAR(512) NOT NULL,
    "storage_region" VARCHAR(64),
    "storage_object_lock_mode" VARCHAR(32),
    "storage_object_lock_retain_until_utc" TIMESTAMPTZ(6),
    "storage_object_lock_legal_hold_status" VARCHAR(16),
    "size_bytes" BIGINT,
    "generated_at_utc" TIMESTAMPTZ(6) NOT NULL,
    "package_type" VARCHAR(64),
    "trust_decision_snapshot" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "verification_packages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "verification_views" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "evidence_id" UUID NOT NULL,
    "viewer_type" "VerificationViewerType" NOT NULL,
    "viewer_user_id" UUID,
    "access_mode" VARCHAR(64),
    "verification_status_snapshot" "VerificationStatus",
    "overall_integrity" BOOLEAN,
    "recorded_integrity_verified" BOOLEAN,
    "access_policy_mode_snapshot" VARCHAR(40),
    "default_preview_item_id_snapshot" UUID,
    "details" JSONB,
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(512),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verification_views_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "workspace_storage_addons" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "owner_user_id" UUID NOT NULL,
    "team_id" UUID,
    "addon_key" "StorageAddonKey" NOT NULL,
    "extra_storage_bytes" BIGINT NOT NULL,
    "billing_cycle" "StorageAddonBillingCycle" NOT NULL,
    "status" "WorkspaceStorageAddonStatus" NOT NULL DEFAULT 'ACTIVE',
    "payment_provider" "PaymentProvider",
    "external_subscription_id" VARCHAR(191),
    "external_payment_id" VARCHAR(191),
    "currency" VARCHAR(8),
    "amount_cents" INTEGER,
    "activated_at_utc" TIMESTAMPTZ(6),
    "current_period_end" TIMESTAMPTZ(6),
    "expires_at_utc" TIMESTAMPTZ(6),
    "canceled_at_utc" TIMESTAMPTZ(6),
    "metadata" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "workspace_storage_addons_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "demo_requests" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "full_name" VARCHAR(160) NOT NULL,
    "work_email" VARCHAR(320) NOT NULL,
    "organization" VARCHAR(180),
    "job_title" VARCHAR(120),
    "country" VARCHAR(120),
    "team_size" VARCHAR(64),
    "use_case" TEXT NOT NULL,
    "message" TEXT,
    "source" VARCHAR(120),
    "source_path" VARCHAR(512),
    "referrer" VARCHAR(2048),
    "utm_source" VARCHAR(160),
    "utm_medium" VARCHAR(160),
    "utm_campaign" VARCHAR(160),
    "utm_term" VARCHAR(160),
    "utm_content" VARCHAR(160),
    "status" "DemoRequestStatus" NOT NULL DEFAULT 'NEW',
    "priority" "DemoRequestPriority" NOT NULL DEFAULT 'NORMAL',
    "lead_quality" "DemoLeadQuality",
    "lead_track" "DemoLeadTrack",
    "recommended_action" "DemoRecommendedAction",
    "routing_target" "DemoRoutingTarget",
    "routing_reason" VARCHAR(255),
    "routed_at" TIMESTAMPTZ(6),
    "routed_by_user_id" UUID,
    "response_sla_hours" INTEGER,
    "qualification_score" INTEGER,
    "qualification_reasons" JSONB,
    "first_responded_at" TIMESTAMPTZ(6),
    "contacted_at" TIMESTAMPTZ(6),
    "contacted_by_user_id" UUID,
    "spam_score" INTEGER NOT NULL DEFAULT 0,
    "spam_reasons" JSONB,
    "is_spam" BOOLEAN NOT NULL DEFAULT false,
    "email_sent_at" TIMESTAMPTZ(6),
    "auto_reply_sent_at" TIMESTAMPTZ(6),
    "webhook_sent_at" TIMESTAMPTZ(6),
    "follow_up_status" "DemoFollowUpStatus" NOT NULL DEFAULT 'ACTIVE',
    "follow_up_step" INTEGER NOT NULL DEFAULT 0,
    "next_follow_up_at" TIMESTAMPTZ(6),
    "last_follow_up_sent_at" TIMESTAMPTZ(6),
    "last_follow_up_template_key" VARCHAR(64),
    "follow_up_stopped_at" TIMESTAMPTZ(6),
    "reviewed_at" TIMESTAMPTZ(6),
    "reviewed_by_user_id" UUID,
    "notes" TEXT,
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(512),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "demo_requests_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "evidence_anchors_evidence_id_key" ON "evidence_anchors"("evidence_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_anchors_provider_idx" ON "evidence_anchors"("provider");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_anchors_mode_idx" ON "evidence_anchors"("mode");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_anchors_anchored_at_utc_idx" ON "evidence_anchors"("anchored_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_certifications_evidence_id_declaration_type_status_idx" ON "evidence_certifications"("evidence_id", "declaration_type", "status", "updated_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_certifications_requested_by_user_id_idx" ON "evidence_certifications"("requested_by_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_certifications_attested_by_user_id_idx" ON "evidence_certifications"("attested_by_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_certifications_attested_at_utc_idx" ON "evidence_certifications"("attested_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_certifications_revoked_at_utc_idx" ON "evidence_certifications"("revoked_at_utc");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "evidence_certifications_evidence_id_declaration_type_versio_key" ON "evidence_certifications"("evidence_id", "declaration_type", "version");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_packages_evidence_id_idx" ON "verification_packages"("evidence_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_packages_generated_at_utc_idx" ON "verification_packages"("generated_at_utc" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_packages_storage_object_lock_mode_idx" ON "verification_packages"("storage_object_lock_mode");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_packages_storage_object_lock_retain_until_utc_idx" ON "verification_packages"("storage_object_lock_retain_until_utc");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "verification_packages_evidence_id_version_key" ON "verification_packages"("evidence_id", "version");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_views_evidence_id_created_at_idx" ON "verification_views"("evidence_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_views_viewer_user_id_idx" ON "verification_views"("viewer_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_views_viewer_type_idx" ON "verification_views"("viewer_type");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_views_verification_status_snapshot_idx" ON "verification_views"("verification_status_snapshot");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_views_overall_integrity_idx" ON "verification_views"("overall_integrity");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_views_recorded_integrity_verified_idx" ON "verification_views"("recorded_integrity_verified");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "verification_views_access_policy_mode_snapshot_idx" ON "verification_views"("access_policy_mode_snapshot");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "workspace_storage_addons_external_subscription_id_key" ON "workspace_storage_addons"("external_subscription_id");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "workspace_storage_addons_external_payment_id_key" ON "workspace_storage_addons"("external_payment_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspace_storage_addons_owner_user_id_status_idx" ON "workspace_storage_addons"("owner_user_id", "status");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspace_storage_addons_team_id_status_idx" ON "workspace_storage_addons"("team_id", "status");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspace_storage_addons_addon_key_status_idx" ON "workspace_storage_addons"("addon_key", "status");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspace_storage_addons_billing_cycle_status_idx" ON "workspace_storage_addons"("billing_cycle", "status");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspace_storage_addons_activated_at_utc_idx" ON "workspace_storage_addons"("activated_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspace_storage_addons_current_period_end_idx" ON "workspace_storage_addons"("current_period_end");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspace_storage_addons_expires_at_utc_idx" ON "workspace_storage_addons"("expires_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspace_storage_addons_canceled_at_utc_idx" ON "workspace_storage_addons"("canceled_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_status_created_at_idx" ON "demo_requests"("status", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_priority_created_at_idx" ON "demo_requests"("priority", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_work_email_idx" ON "demo_requests"("work_email");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_lead_quality_created_at_idx" ON "demo_requests"("lead_quality", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_lead_track_created_at_idx" ON "demo_requests"("lead_track", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_recommended_action_created_at_idx" ON "demo_requests"("recommended_action", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_response_sla_hours_idx" ON "demo_requests"("response_sla_hours");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_contacted_at_created_at_idx" ON "demo_requests"("contacted_at", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_organization_idx" ON "demo_requests"("organization");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_source_created_at_idx" ON "demo_requests"("source", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_is_spam_created_at_idx" ON "demo_requests"("is_spam", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_created_at_idx" ON "demo_requests"("created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_routing_target_created_at_idx" ON "demo_requests"("routing_target", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_follow_up_status_next_follow_up_at_idx" ON "demo_requests"("follow_up_status", "next_follow_up_at");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "demo_requests_lead_track_follow_up_status_created_at_idx" ON "demo_requests"("lead_track", "follow_up_status", "created_at" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "case_status_history_toStatus_idx" ON "case_status_history"("toStatus");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "custody_events_event_hash_idx" ON "custody_events"("event_hash");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_delete_scheduled_for_utc_idx" ON "evidence"("delete_scheduled_for_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_owner_user_id_deleted_at_idx" ON "evidence"("owner_user_id", "deleted_at");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_owner_user_id_delete_scheduled_for_utc_idx" ON "evidence"("owner_user_id", "delete_scheduled_for_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_storage_bucket_storage_key_idx" ON "evidence"("storage_bucket", "storage_key");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_storage_object_lock_mode_idx" ON "evidence"("storage_object_lock_mode");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_storage_object_lock_retain_until_utc_idx" ON "evidence"("storage_object_lock_retain_until_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_capture_method_idx" ON "evidence"("capture_method");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_identity_level_snapshot_idx" ON "evidence"("identity_level_snapshot");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_submitted_by_user_id_idx" ON "evidence"("submitted_by_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_created_by_user_id_idx" ON "evidence"("created_by_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_uploaded_by_user_id_idx" ON "evidence"("uploaded_by_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_last_accessed_by_user_id_idx" ON "evidence"("last_accessed_by_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_last_accessed_at_utc_idx" ON "evidence"("last_accessed_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_verification_status_idx" ON "evidence"("verification_status");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_recorded_integrity_verified_at_utc_idx" ON "evidence"("recorded_integrity_verified_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_last_verified_at_utc_idx" ON "evidence"("last_verified_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_review_ready_at_utc_idx" ON "evidence"("review_ready_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_latest_report_version_idx" ON "evidence"("latest_report_version");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_verification_package_version_idx" ON "evidence"("verification_package_version");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_ots_hash_idx" ON "evidence"("ots_hash");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_ots_status_idx" ON "evidence"("ots_status");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_ots_anchored_at_utc_idx" ON "evidence"("ots_anchored_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_parts_storage_bucket_storage_key_idx" ON "evidence_parts"("storage_bucket", "storage_key");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_parts_storage_object_lock_mode_idx" ON "evidence_parts"("storage_object_lock_mode");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_parts_storage_object_lock_retain_until_utc_idx" ON "evidence_parts"("storage_object_lock_retain_until_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_parts_uploaded_by_user_id_idx" ON "evidence_parts"("uploaded_by_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "evidence_parts_uploaded_at_utc_idx" ON "evidence_parts"("uploaded_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "payments_team_id_created_at_idx" ON "payments"("team_id", "created_at");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "reports_storage_object_lock_mode_idx" ON "reports"("storage_object_lock_mode");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "reports_storage_object_lock_retain_until_utc_idx" ON "reports"("storage_object_lock_retain_until_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "reports_verification_status_snapshot_idx" ON "reports"("verification_status_snapshot");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "security_events_teamId_createdAtUtc_idx" ON "security_events"("teamId", "createdAtUtc" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "security_events_severity_createdAtUtc_idx" ON "security_events"("severity", "createdAtUtc" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "security_events_eventType_createdAtUtc_idx" ON "security_events"("eventType", "createdAtUtc" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "security_events_createdAtUtc_idx" ON "security_events"("createdAtUtc" DESC);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "subscriptions_team_id_status_idx" ON "subscriptions"("team_id", "status");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "teams_owner_user_id_idx" ON "teams"("owner_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "teams_billing_owner_user_id_idx" ON "teams"("billing_owner_user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "teams_billing_plan_idx" ON "teams"("billing_plan");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "teams_billing_status_idx" ON "teams"("billing_status");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "teams_over_seat_limit_idx" ON "teams"("over_seat_limit");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "teams_verification_state_idx" ON "teams"("verification_state");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "teams_verified_at_utc_idx" ON "teams"("verified_at_utc");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "users_email_verified_at_idx" ON "users"("email_verified_at");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "users_organization_verification_state_idx" ON "users"("organization_verification_state");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "users_current_workspace_id_idx" ON "users"("current_workspace_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspace_governance_policies_team_id_idx" ON "workspace_governance_policies"("team_id");

-- RenameForeignKey
ALTER TABLE "api_credential_usage_logs" RENAME CONSTRAINT "api_credential_usage_logs_credential_fkey" TO "api_credential_usage_logs_api_credential_id_fkey";

-- RenameForeignKey
ALTER TABLE "api_credentials" RENAME CONSTRAINT "api_credentials_created_by_fkey" TO "api_credentials_created_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "api_credentials" RENAME CONSTRAINT "api_credentials_revoked_by_fkey" TO "api_credentials_revoked_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "api_credentials" RENAME CONSTRAINT "api_credentials_team_fkey" TO "api_credentials_team_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_rules" RENAME CONSTRAINT "automation_rules_created_by_fkey" TO "automation_rules_created_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_rules" RENAME CONSTRAINT "automation_rules_team_fkey" TO "automation_rules_team_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_rules" RENAME CONSTRAINT "automation_rules_updated_by_fkey" TO "automation_rules_updated_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_runs" RENAME CONSTRAINT "automation_runs_rule_fkey" TO "automation_runs_rule_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_runs" RENAME CONSTRAINT "automation_runs_team_fkey" TO "automation_runs_team_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_webhook_deliveries" RENAME CONSTRAINT "automation_webhook_deliveries_destination_fkey" TO "automation_webhook_deliveries_destination_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_webhook_deliveries" RENAME CONSTRAINT "automation_webhook_deliveries_run_fkey" TO "automation_webhook_deliveries_run_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_webhook_deliveries" RENAME CONSTRAINT "automation_webhook_deliveries_team_fkey" TO "automation_webhook_deliveries_team_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_webhook_destinations" RENAME CONSTRAINT "automation_webhook_destinations_created_by_fkey" TO "automation_webhook_destinations_created_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_webhook_destinations" RENAME CONSTRAINT "automation_webhook_destinations_team_fkey" TO "automation_webhook_destinations_team_id_fkey";

-- RenameForeignKey
ALTER TABLE "automation_webhook_destinations" RENAME CONSTRAINT "automation_webhook_destinations_updated_by_fkey" TO "automation_webhook_destinations_updated_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "case_legal_holds" RENAME CONSTRAINT "case_legal_holds_case_fkey" TO "case_legal_holds_case_id_fkey";

-- RenameForeignKey
ALTER TABLE "discussion_mentions" RENAME CONSTRAINT "discussion_mentions_message_fkey" TO "discussion_mentions_message_id_fkey";

-- RenameForeignKey
ALTER TABLE "discussion_messages" RENAME CONSTRAINT "discussion_messages_thread_fkey" TO "discussion_messages_thread_id_fkey";

-- RenameForeignKey
ALTER TABLE "discussion_participants" RENAME CONSTRAINT "discussion_participants_thread_fkey" TO "discussion_participants_thread_id_fkey";

-- RenameForeignKey
ALTER TABLE "discussion_threads" RENAME CONSTRAINT "discussion_threads_evidence_fkey" TO "discussion_threads_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_entities" RENAME CONSTRAINT "evidence_entities_evidence_fkey" TO "evidence_entities_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_extracted_texts" RENAME CONSTRAINT "evidence_extracted_texts_evidence_fkey" TO "evidence_extracted_texts_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_intelligence_jobs" RENAME CONSTRAINT "evidence_intelligence_jobs_evidence_fkey" TO "evidence_intelligence_jobs_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_legal_holds" RENAME CONSTRAINT "evidence_legal_holds_evidence_fkey" TO "evidence_legal_holds_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_legal_holds" RENAME CONSTRAINT "evidence_legal_holds_placed_by_user_fkey" TO "evidence_legal_holds_placed_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_legal_holds" RENAME CONSTRAINT "evidence_legal_holds_released_by_user_fkey" TO "evidence_legal_holds_released_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_legal_holds" RENAME CONSTRAINT "evidence_legal_holds_team_fkey" TO "evidence_legal_holds_team_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_request_deliverables" RENAME CONSTRAINT "evidence_request_deliverables_request_fkey" TO "evidence_request_deliverables_evidence_request_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_request_events" RENAME CONSTRAINT "evidence_request_events_actor_user_fkey" TO "evidence_request_events_actor_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_request_events" RENAME CONSTRAINT "evidence_request_events_request_fkey" TO "evidence_request_events_evidence_request_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_request_responses" RENAME CONSTRAINT "evidence_request_responses_intake_session_fkey" TO "evidence_request_responses_intake_session_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_request_responses" RENAME CONSTRAINT "evidence_request_responses_request_fkey" TO "evidence_request_responses_evidence_request_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_request_responses" RENAME CONSTRAINT "evidence_request_responses_response_evidence_fkey" TO "evidence_request_responses_response_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_request_responses" RENAME CONSTRAINT "evidence_request_responses_reviewed_by_user_fkey" TO "evidence_request_responses_reviewed_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_request_responses" RENAME CONSTRAINT "evidence_request_responses_submitted_by_user_fkey" TO "evidence_request_responses_submitted_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_review_workflows" RENAME CONSTRAINT "evidence_review_workflows_escalated_by_fkey" TO "evidence_review_workflows_escalated_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_review_workflows" RENAME CONSTRAINT "evidence_review_workflows_reopened_by_fkey" TO "evidence_review_workflows_reopened_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_semantic_chunks" RENAME CONSTRAINT "evidence_semantic_chunks_evidence_fkey" TO "evidence_semantic_chunks_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_similarities" RENAME CONSTRAINT "evidence_similarities_source_fkey" TO "evidence_similarities_source_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "evidence_similarities" RENAME CONSTRAINT "evidence_similarities_target_fkey" TO "evidence_similarities_target_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "file_security_scans" RENAME CONSTRAINT "file_security_scans_evidence_fkey" TO "file_security_scans_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "integration_webhook_deliveries" RENAME CONSTRAINT "integration_webhook_deliveries_endpoint_fkey" TO "integration_webhook_deliveries_endpoint_id_fkey";

-- RenameForeignKey
ALTER TABLE "integration_webhook_endpoints" RENAME CONSTRAINT "integration_webhook_endpoints_created_by_fkey" TO "integration_webhook_endpoints_created_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "integration_webhook_endpoints" RENAME CONSTRAINT "integration_webhook_endpoints_team_fkey" TO "integration_webhook_endpoints_team_id_fkey";

-- RenameForeignKey
ALTER TABLE "notification_deliveries" RENAME CONSTRAINT "notification_deliveries_evidence_request_fkey" TO "notification_deliveries_evidence_request_id_fkey";

-- RenameForeignKey
ALTER TABLE "notification_deliveries" RENAME CONSTRAINT "notification_deliveries_initiated_by_user_fkey" TO "notification_deliveries_initiated_by_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "notification_deliveries" RENAME CONSTRAINT "notification_deliveries_recipient_user_fkey" TO "notification_deliveries_recipient_user_id_fkey";

-- RenameForeignKey
ALTER TABLE "upload_sessions" RENAME CONSTRAINT "upload_sessions_evidence_fkey" TO "upload_sessions_evidence_id_fkey";

-- RenameForeignKey
ALTER TABLE "workspace_governance_policies" RENAME CONSTRAINT "workspace_governance_policies_team_fkey" TO "workspace_governance_policies_team_id_fkey";

-- RenameForeignKey
ALTER TABLE "workspace_governance_policies" RENAME CONSTRAINT "workspace_governance_policies_updated_by_user_fkey" TO "workspace_governance_policies_updated_by_user_id_fkey";

-- AddForeignKey
ALTER TABLE "evidence" ADD CONSTRAINT "evidence_guest_identity_id_fkey" FOREIGN KEY ("guest_identity_id") REFERENCES "guest_identities"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_anchors" ADD CONSTRAINT "evidence_anchors_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_parts" ADD CONSTRAINT "evidence_parts_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_certifications" ADD CONSTRAINT "evidence_certifications_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_packages" ADD CONSTRAINT "verification_packages_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_views" ADD CONSTRAINT "verification_views_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teams" ADD CONSTRAINT "teams_owner_user_id_fkey" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teams" ADD CONSTRAINT "teams_billing_owner_user_id_fkey" FOREIGN KEY ("billing_owner_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_storage_addons" ADD CONSTRAINT "workspace_storage_addons_owner_user_id_fkey" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_storage_addons" ADD CONSTRAINT "workspace_storage_addons_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_access_granted_by_user_id_fkey" FOREIGN KEY ("access_granted_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_suspended_by_user_id_fkey" FOREIGN KEY ("suspended_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_revoked_by_user_id_fkey" FOREIGN KEY ("revoked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "case_access" ADD CONSTRAINT "case_access_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "case_access" ADD CONSTRAINT "case_access_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_invites" ADD CONSTRAINT "team_invites_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "guest_identities" ADD CONSTRAINT "guest_identities_claimed_by_user_id_fkey" FOREIGN KEY ("claimed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "guest_identities" ADD CONSTRAINT "guest_identities_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "entitlements" ADD CONSTRAINT "entitlements_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workflow_intake_sessions" ADD CONSTRAINT "workflow_intake_sessions_revoked_by_user_id_fkey" FOREIGN KEY ("revoked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "api_credentials" ADD CONSTRAINT "api_credentials_disabled_by_user_id_fkey" FOREIGN KEY ("disabled_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "member_capability_grants" ADD CONSTRAINT "member_capability_grants_team_member_id_fkey" FOREIGN KEY ("team_member_id") REFERENCES "team_members"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "member_capability_grants" ADD CONSTRAINT "member_capability_grants_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "member_capability_grants" ADD CONSTRAINT "member_capability_grants_granted_by_user_id_fkey" FOREIGN KEY ("granted_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "member_capability_grants" ADD CONSTRAINT "member_capability_grants_revoked_by_user_id_fkey" FOREIGN KEY ("revoked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "member_delegated_admin_scopes" ADD CONSTRAINT "member_delegated_admin_scopes_team_member_id_fkey" FOREIGN KEY ("team_member_id") REFERENCES "team_members"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "member_delegated_admin_scopes" ADD CONSTRAINT "member_delegated_admin_scopes_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "member_delegated_admin_scopes" ADD CONSTRAINT "member_delegated_admin_scopes_granted_by_user_id_fkey" FOREIGN KEY ("granted_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "member_delegated_admin_scopes" ADD CONSTRAINT "member_delegated_admin_scopes_revoked_by_user_id_fkey" FOREIGN KEY ("revoked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "organization_security_policies" ADD CONSTRAINT "organization_security_policies_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "organization_security_policies" ADD CONSTRAINT "organization_security_policies_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "access_reviews" ADD CONSTRAINT "access_reviews_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "access_reviews" ADD CONSTRAINT "access_reviews_initiated_by_user_id_fkey" FOREIGN KEY ("initiated_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "access_reviews" ADD CONSTRAINT "access_reviews_completed_by_user_id_fkey" FOREIGN KEY ("completed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "access_reviews" ADD CONSTRAINT "access_reviews_subject_user_id_fkey" FOREIGN KEY ("subject_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "external_identity_mappings" ADD CONSTRAINT "external_identity_mappings_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "external_identity_mappings" ADD CONSTRAINT "external_identity_mappings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "communication_messages" ADD CONSTRAINT "communication_messages_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "communication_messages" ADD CONSTRAINT "communication_messages_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "communication_messages" ADD CONSTRAINT "communication_messages_related_evidence_id_fkey" FOREIGN KEY ("related_evidence_id") REFERENCES "evidence"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "communication_messages" ADD CONSTRAINT "communication_messages_related_evidence_request_id_fkey" FOREIGN KEY ("related_evidence_request_id") REFERENCES "evidence_requests"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "communication_messages" ADD CONSTRAINT "communication_messages_related_discussion_thread_id_fkey" FOREIGN KEY ("related_discussion_thread_id") REFERENCES "discussion_threads"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "communication_messages" ADD CONSTRAINT "communication_messages_related_intake_session_id_fkey" FOREIGN KEY ("related_intake_session_id") REFERENCES "workflow_intake_sessions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "communication_preferences" ADD CONSTRAINT "communication_preferences_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "communication_preferences" ADD CONSTRAINT "communication_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_attempts" ADD CONSTRAINT "verification_attempts_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_attempts" ADD CONSTRAINT "verification_attempts_initiated_by_user_id_fkey" FOREIGN KEY ("initiated_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "step_up_challenges" ADD CONSTRAINT "step_up_challenges_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "step_up_challenges" ADD CONSTRAINT "step_up_challenges_initiated_by_user_id_fkey" FOREIGN KEY ("initiated_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trusted_devices" ADD CONSTRAINT "trusted_devices_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trusted_devices" ADD CONSTRAINT "trusted_devices_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trusted_devices" ADD CONSTRAINT "trusted_devices_revoked_by_user_id_fkey" FOREIGN KEY ("revoked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "revoked_sessions" ADD CONSTRAINT "revoked_sessions_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "revoked_sessions" ADD CONSTRAINT "revoked_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "revoked_sessions" ADD CONSTRAINT "revoked_sessions_revoked_by_user_id_fkey" FOREIGN KEY ("revoked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "risk_signals" ADD CONSTRAINT "risk_signals_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "risk_signals" ADD CONSTRAINT "risk_signals_subject_user_id_fkey" FOREIGN KEY ("subject_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "operational_incidents" ADD CONSTRAINT "operational_incidents_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "operational_incidents" ADD CONSTRAINT "operational_incidents_acknowledged_by_user_id_fkey" FOREIGN KEY ("acknowledged_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "operational_incidents" ADD CONSTRAINT "operational_incidents_resolved_by_user_id_fkey" FOREIGN KEY ("resolved_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "operational_incident_events" ADD CONSTRAINT "operational_incident_events_incident_id_fkey" FOREIGN KEY ("incident_id") REFERENCES "operational_incidents"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_instances" ADD CONSTRAINT "evidence_workflow_instances_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_instances" ADD CONSTRAINT "evidence_workflow_instances_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "evidence_workflow_templates"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_instances" ADD CONSTRAINT "evidence_workflow_instances_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_instances" ADD CONSTRAINT "evidence_workflow_instances_assigned_reviewer_user_id_fkey" FOREIGN KEY ("assigned_reviewer_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_instances" ADD CONSTRAINT "evidence_workflow_instances_evidence_request_id_fkey" FOREIGN KEY ("evidence_request_id") REFERENCES "evidence_requests"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_instances" ADD CONSTRAINT "evidence_workflow_instances_intake_session_id_fkey" FOREIGN KEY ("intake_session_id") REFERENCES "workflow_intake_sessions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_instance_evidence" ADD CONSTRAINT "evidence_workflow_instance_evidence_workflow_instance_id_fkey" FOREIGN KEY ("workflow_instance_id") REFERENCES "evidence_workflow_instances"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_step_instances" ADD CONSTRAINT "evidence_workflow_step_instances_workflow_instance_id_fkey" FOREIGN KEY ("workflow_instance_id") REFERENCES "evidence_workflow_instances"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_step_instances" ADD CONSTRAINT "evidence_workflow_step_instances_completed_by_user_id_fkey" FOREIGN KEY ("completed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_step_instances" ADD CONSTRAINT "evidence_workflow_step_instances_mapped_evidence_id_fkey" FOREIGN KEY ("mapped_evidence_id") REFERENCES "evidence"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_visibility_decisions" ADD CONSTRAINT "evidence_workflow_visibility_decisions_workflow_instance_i_fkey" FOREIGN KEY ("workflow_instance_id") REFERENCES "evidence_workflow_instances"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_workflow_visibility_decisions" ADD CONSTRAINT "evidence_workflow_visibility_decisions_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_search_documents" ADD CONSTRAINT "evidence_search_documents_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_search_views" ADD CONSTRAINT "saved_search_views_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_search_views" ADD CONSTRAINT "saved_search_views_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_escalations" ADD CONSTRAINT "review_escalations_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_escalations" ADD CONSTRAINT "review_escalations_workflow_id_fkey" FOREIGN KEY ("workflow_id") REFERENCES "evidence_review_workflows"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_escalations" ADD CONSTRAINT "review_escalations_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_escalations" ADD CONSTRAINT "review_escalations_assigned_to_user_id_fkey" FOREIGN KEY ("assigned_to_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_escalations" ADD CONSTRAINT "review_escalations_acknowledged_by_user_id_fkey" FOREIGN KEY ("acknowledged_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_escalations" ADD CONSTRAINT "review_escalations_resolved_by_user_id_fkey" FOREIGN KEY ("resolved_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviewer_workload_snapshots" ADD CONSTRAINT "reviewer_workload_snapshots_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviewer_workload_snapshots" ADD CONSTRAINT "reviewer_workload_snapshots_reviewer_user_id_fkey" FOREIGN KEY ("reviewer_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviewer_ops_reminders" ADD CONSTRAINT "reviewer_ops_reminders_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sso_connections" ADD CONSTRAINT "sso_connections_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sso_connections" ADD CONSTRAINT "sso_connections_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scim_provisioning_tokens" ADD CONSTRAINT "scim_provisioning_tokens_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scim_provisioning_tokens" ADD CONSTRAINT "scim_provisioning_tokens_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "authenticated_sessions" ADD CONSTRAINT "authenticated_sessions_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "authenticated_sessions" ADD CONSTRAINT "authenticated_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sso_callback_attempts" ADD CONSTRAINT "sso_callback_attempts_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sso_callback_attempts" ADD CONSTRAINT "sso_callback_attempts_sso_connection_id_fkey" FOREIGN KEY ("sso_connection_id") REFERENCES "sso_connections"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scim_groups" ADD CONSTRAINT "scim_groups_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_retention_policies" ADD CONSTRAINT "evidence_retention_policies_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_retention_policies" ADD CONSTRAINT "evidence_retention_policies_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_retention_policy_versions" ADD CONSTRAINT "evidence_retention_policy_versions_retention_policy_id_fkey" FOREIGN KEY ("retention_policy_id") REFERENCES "evidence_retention_policies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_retention_policy_versions" ADD CONSTRAINT "evidence_retention_policy_versions_authored_by_user_id_fkey" FOREIGN KEY ("authored_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "destruction_reviews" ADD CONSTRAINT "destruction_reviews_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "destruction_reviews" ADD CONSTRAINT "destruction_reviews_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "destruction_reviews" ADD CONSTRAINT "destruction_reviews_initiated_by_user_id_fkey" FOREIGN KEY ("initiated_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "destruction_reviews" ADD CONSTRAINT "destruction_reviews_decided_by_user_id_fkey" FOREIGN KEY ("decided_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_lifecycle_events" ADD CONSTRAINT "evidence_lifecycle_events_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_lifecycle_events" ADD CONSTRAINT "evidence_lifecycle_events_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "governance_reconciliation_runs" ADD CONSTRAINT "governance_reconciliation_runs_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "governance_reconciliation_runs" ADD CONSTRAINT "governance_reconciliation_runs_triggered_by_user_id_fkey" FOREIGN KEY ("triggered_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "destruction_executions" ADD CONSTRAINT "destruction_executions_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "destruction_executions" ADD CONSTRAINT "destruction_executions_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "destruction_executions" ADD CONSTRAINT "destruction_executions_destruction_review_id_fkey" FOREIGN KEY ("destruction_review_id") REFERENCES "destruction_reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "destruction_executions" ADD CONSTRAINT "destruction_executions_executed_by_user_id_fkey" FOREIGN KEY ("executed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "immutable_storage_checks" ADD CONSTRAINT "immutable_storage_checks_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "immutable_storage_checks" ADD CONSTRAINT "immutable_storage_checks_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "governance_notifications" ADD CONSTRAINT "governance_notifications_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "governance_notifications" ADD CONSTRAINT "governance_notifications_related_evidence_id_fkey" FOREIGN KEY ("related_evidence_id") REFERENCES "evidence"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "governance_export_snapshots" ADD CONSTRAINT "governance_export_snapshots_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "governance_export_snapshots" ADD CONSTRAINT "governance_export_snapshots_evidence_id_fkey" FOREIGN KEY ("evidence_id") REFERENCES "evidence"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "governance_export_snapshots" ADD CONSTRAINT "governance_export_snapshots_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspace_persona_profiles" ADD CONSTRAINT "workspace_persona_profiles_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

